package com.ares.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAccountUpdate<M extends BaseAccountUpdate<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setAccountId(java.lang.String accountId) {
		set("accountId", accountId);
	}

	public java.lang.String getAccountId() {
		return get("accountId");
	}

	public void setUpdateType(java.lang.Integer updateType) {
		set("updateType", updateType);
	}

	public java.lang.Integer getUpdateType() {
		return get("updateType");
	}

	public void setBeforeUpdate(java.lang.String beforeUpdate) {
		set("beforeUpdate", beforeUpdate);
	}

	public java.lang.String getBeforeUpdate() {
		return get("beforeUpdate");
	}

	public void setAfterUpdate(java.lang.String afterUpdate) {
		set("afterUpdate", afterUpdate);
	}

	public java.lang.String getAfterUpdate() {
		return get("afterUpdate");
	}

	public void setDescribe(java.lang.String describe) {
		set("describe", describe);
	}

	public java.lang.String getDescribe() {
		return get("describe");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
