package com.ares.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAccount<M extends BaseAccount<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setIdentiyId(java.lang.String identiyId) {
		set("identiyId", identiyId);
	}

	public java.lang.String getIdentiyId() {
		return get("identiyId");
	}

	public void setIdentiyCode(java.lang.String identiyCode) {
		set("identiyCode", identiyCode);
	}

	public java.lang.String getIdentiyCode() {
		return get("identiyCode");
	}

	public void setPhoneNo(java.lang.String phoneNo) {
		set("phoneNo", phoneNo);
	}

	public java.lang.String getPhoneNo() {
		return get("phoneNo");
	}

	public void setPayCode(java.lang.String payCode) {
		set("payCode", payCode);
	}

	public java.lang.String getPayCode() {
		return get("payCode");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
