package com.arnold.server.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("tb_accredited", "id", Accredited.class);
		arp.addMapping("tb_area", "id", Area.class);
		arp.addMapping("tb_arnold", "id", Arnold.class);
		arp.addMapping("tb_backstagecrew", "id", Backstagecrew.class);
		arp.addMapping("tb_breed_income", "id", BreedIncome.class);
		arp.addMapping("tb_bussiness_org", "id", BussinessOrg.class);
		arp.addMapping("tb_bussiness_type", "id", BussinessType.class);
		arp.addMapping("tb_collective_economy", "id", CollectiveEconomy.class);
		arp.addMapping("tb_collective_economy_purchase_happen", "id", CollectiveEconomyPurchaseHappen.class);
		arp.addMapping("tb_collective_economy_sell_happen", "id", CollectiveEconomySellHappen.class);
		arp.addMapping("tb_cultivation_income", "id", CultivationIncome.class);
		arp.addMapping("tb_education", "id", Education.class);
		arp.addMapping("tb_education_participant", "id", EducationParticipant.class);
		arp.addMapping("tb_enterprise", "id", Enterprise.class);
		arp.addMapping("tb_enterprise_measure_relation", "id", EnterpriseMeasureRelation.class);
		arp.addMapping("tb_enterprise_village_relation", "id", EnterpriseVillageRelation.class);
		arp.addMapping("tb_family", "id", Family.class);
		arp.addMapping("tb_family_burden_relation", "id", FamilyBurdenRelation.class);
		arp.addMapping("tb_family_condition_relation", "id", FamilyConditionRelation.class);
		arp.addMapping("tb_family_economic", "id", FamilyEconomic.class);
		arp.addMapping("tb_family_economic_herds", "id", FamilyEconomicHerds.class);
		arp.addMapping("tb_family_economic_purchase_happen", "id", FamilyEconomicPurchaseHappen.class);
		arp.addMapping("tb_family_economic_self_sale_happen", "id", FamilyEconomicSelfSaleHappen.class);
		arp.addMapping("tb_family_economic_special_situation_happen", "id", FamilyEconomicSpecialSituationHappen.class);
		arp.addMapping("tb_family_economic_underwriting_happen", "id", FamilyEconomicUnderwritingHappen.class);
		arp.addMapping("tb_family_insurance_relation", "id", FamilyInsuranceRelation.class);
		arp.addMapping("tb_family_livecondition", "familyId", FamilyLivecondition.class);
		arp.addMapping("tb_family_measure_relation", "id", FamilyMeasureRelation.class);
		arp.addMapping("tb_family_poverty_happen", "id", FamilyPovertyHappen.class);
		arp.addMapping("tb_family_removal_happen", "id", FamilyRemovalHappen.class);
		arp.addMapping("tb_family_shift_income_happen", "id", FamilyShiftIncomeHappen.class);
		arp.addMapping("tb_family_soldierdepentant_relation", "id", FamilySoldierdepentantRelation.class);
		arp.addMapping("tb_family_status", "id", FamilyStatus.class);
		arp.addMapping("tb_family_warning_happen", "id", FamilyWarningHappen.class);
		arp.addMapping("tb_group", "id", Group.class);
		arp.addMapping("tb_help", "id", Help.class);
		arp.addMapping("tb_honor", "id", Honor.class);
		arp.addMapping("tb_house", "id", House.class);
		arp.addMapping("tb_house_condition_relation", "id", HouseConditionRelation.class);
		arp.addMapping("tb_industry", "id", Industry.class);
		arp.addMapping("tb_leader", "id", Leader.class);
		arp.addMapping("tb_leader_department_relation", "id", LeaderDepartmentRelation.class);
		arp.addMapping("tb_leader_region_relation", "id", LeaderRegionRelation.class);
		arp.addMapping("tb_locate_village", "id", LocateVillage.class);
		arp.addMapping("tb_locate_village_happen", "id", LocateVillageHappen.class);
		arp.addMapping("tb_member", "id", Member.class);
		arp.addMapping("tb_member_commend_happen", "id", MemberCommendHappen.class);
		arp.addMapping("tb_member_family_happen", "id", MemberFamilyHappen.class);
		arp.addMapping("tb_member_family_relation", "id", MemberFamilyRelation.class);
		arp.addMapping("tb_member_org_happen", "id", MemberOrgHappen.class);
		arp.addMapping("tb_member_region_relation", "id", MemberRegionRelation.class);
		arp.addMapping("tb_org_member_relation", "id", OrgMemberRelation.class);
		arp.addMapping("tb_post", "id", Post.class);
		arp.addMapping("tb_post_company", "id", PostCompany.class);
		arp.addMapping("tb_poverty_count", "id", PovertyCount.class);
		arp.addMapping("tb_product_condition", "id", ProductCondition.class);
		arp.addMapping("tb_project", "id", Project.class);
		arp.addMapping("tb_project_invest_happen", "id", ProjectInvestHappen.class);
		arp.addMapping("tb_project_progress", "id", ProjectProgress.class);
		arp.addMapping("tb_project_region_relation", "id", ProjectRegionRelation.class);
		arp.addMapping("tb_project_statistics", "id", ProjectStatistics.class);
		arp.addMapping("tb_property_village", "id", PropertyVillage.class);
		arp.addMapping("tb_public_service", "id", PublicService.class);
		arp.addMapping("tb_public_service_invest_happen", "id", PublicServiceInvestHappen.class);
		arp.addMapping("tb_region", "id", Region.class);
		arp.addMapping("tb_region_cause_relation", "id", RegionCauseRelation.class);
		arp.addMapping("tb_region_industry_happen", "id", RegionIndustryHappen.class);
		arp.addMapping("tb_region_industry_income_happen", "id", RegionIndustryIncomeHappen.class);
		arp.addMapping("tb_region_info", "id", RegionInfo.class);
		arp.addMapping("tb_region_invest_happen", "id", RegionInvestHappen.class);
		arp.addMapping("tb_static_family_income", "id", StaticFamilyIncome.class);
		arp.addMapping("tb_statistics_poverty_effect", "id", StatisticsPovertyEffect.class);
		arp.addMapping("tb_statistics_poverty_income", "id", StatisticsPovertyIncome.class);
		arp.addMapping("tb_statistics_poverty_reason", "id", StatisticsPovertyReason.class);
		arp.addMapping("tb_statistics_project", "id", StatisticsProject.class);
		arp.addMapping("tb_train", "id", Train.class);
		arp.addMapping("tb_train_has_job", "id", TrainHasJob.class);
		arp.addMapping("tb_train_participant", "id", TrainParticipant.class);
		arp.addMapping("tb_train_speaker", "id", TrainSpeaker.class);
		arp.addMapping("tb_underwriter", "id", Underwriter.class);
		arp.addMapping("tb_valiger_edu_happen", "id", ValigerEduHappen.class);
		arp.addMapping("tb_valiger_train_happen", "id", ValigerTrainHappen.class);
		arp.addMapping("tb_villager", "id", Villager.class);
		arp.addMapping("tb_villager_family_happen", "id", VillagerFamilyHappen.class);
		arp.addMapping("tb_villager_industry_income_happen", "id", VillagerIndustryIncomeHappen.class);
		arp.addMapping("tb_villager_post_happen", "id", VillagerPostHappen.class);
		arp.addMapping("tb_villager_post_happen_bak", "id", VillagerPostHappenBak.class);
		arp.addMapping("tb_villager_post_income_happen", "id", VillagerPostIncomeHappen.class);
		arp.addMapping("tb_villager_post_relation", "id", VillagerPostRelation.class);
		arp.addMapping("tb_visit_count", "id", VisitCount.class);
		arp.addMapping("tb_work_post", "id", WorkPost.class);
		arp.addMapping("team_help", "id", TeamHelp.class);
		arp.addMapping("team_info", "id", TeamInfo.class);
		arp.addMapping("team_info_detail", "id", TeamInfoDetail.class);
	}
}

