package com.arnold.server.model;

import com.arnold.server.model.base.BaseAccredited;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Accredited extends BaseAccredited<Accredited> {
	public static final Accredited dao = new Accredited();
	String tableName = "tb_accredited";
	
	
	public Accredited findByMemberId(String memberId) {
		
		String sql = "Select * from " + tableName + " where memberId=?";
		return dao.findFirst(sql, memberId);
	}
}
