package com.arnold.server.model;

import com.arnold.server.model.base.BaseBussinessOrg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BussinessOrg extends BaseBussinessOrg<BussinessOrg> {
	public static final BussinessOrg dao = new BussinessOrg();
}

