package com.arnold.server.model;

import com.arnold.server.model.base.BaseBussinessType;
import com.jfinal.plugin.activerecord.Page;
import com.pallas.utils.Utils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BussinessType extends BaseBussinessType<BussinessType> {
	public static final BussinessType dao = new BussinessType();
	
	public Page<BussinessType> pageBussinessTypeByIds(int pageNumber, int pageSize, String ids){
		
		String sql = "SELECT *";
		
		String sqlExceptSelect = " FROM tb_bussiness_type t1 WHERE 1 = 1";
		
		if(!Utils.isBlankOrEmpty(ids)){
			
			String[] idStrArr = ids.split(",");
			
			for(String str : idStrArr){
				
				sqlExceptSelect += " OR t1.id = '" + str + "'";
				
			}
		}
		
		return dao.paginate(pageNumber, pageSize, sql, sqlExceptSelect);
				
	}
	
}
