package com.arnold.server.model;

import com.arnold.server.model.base.BaseCollectiveEconomyPurchaseHappen;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CollectiveEconomyPurchaseHappen extends BaseCollectiveEconomyPurchaseHappen<CollectiveEconomyPurchaseHappen> {
	public static final CollectiveEconomyPurchaseHappen dao = new CollectiveEconomyPurchaseHappen();
	public static final String TABLE_NAME = "tb_collective_economy_purchase_happen";
	/**
	 * @Description:保存集体经济采购信息
	 * @author Li Bangming;
	 * @date 2017年8月18日 下午3:38:41
	 * @collectiveEconomy 集体经济采购信息对象
	 * @return
	 */
	public  boolean saveCollectiveEconomyPurchaseHappen(CollectiveEconomyPurchaseHappen collectiveEconomyPurchaseHappen) {
	    boolean isSave=	collectiveEconomyPurchaseHappen.save();
		return isSave;
	}
	/**
	 * @Description:根据id查询集体经济采购信息
	 * @author Li Bangming;
	 * @date 2017年8月18日 下午3:38:41
	 * @collectiveEconomy 集体经济采购信息对象
	 * @return
	 */
	public  static  CollectiveEconomyPurchaseHappen queryCollectiveEconomyPurchaseHappenById(String id) {
		return dao.findById(id);
	}
	
	/**
	 * @Description:保存集体经济采购信息
	 * @author Li Bangming;
	 * @date 2017年8月18日 下午3:38:41
	 * @collectiveEconomy 集体经济采购信息对象
	 * @return
	 */
	public  boolean updateCollectiveEconomyPurchaseHappen(CollectiveEconomyPurchaseHappen collectiveEconomyPurchaseHappen) {
	    boolean isUpdate=collectiveEconomyPurchaseHappen.update();
		return isUpdate;
	}
	/**
	 * @Description:分页集体经济采购信息
	 * @author Li Bangming;
	 * @date 2017年8月18日 下午3:38:41
	 * @return
	 */
	public static Page<CollectiveEconomyPurchaseHappen>  pageCollectiveEconomyPurchaseHappen(int pageNumber,int pageSize,String collectiveEconomyId,String regionId){
 		String select=" select tvpi.*,(select name from tb_enterprise te where te.id=tvpi.orgId) as orgName ";
		String sqlExceptSelect="   from "+TABLE_NAME+" tvpi where collectiveEconomyId like '"+collectiveEconomyId+"' or regionId like '"+regionId+"' order by tvpi.createTime DESC";
		return dao.paginate(pageNumber, pageSize, select, sqlExceptSelect);
	}
}
