package com.arnold.server.model;

import com.arnold.server.model.base.BaseCollectiveEconomySellHappen;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CollectiveEconomySellHappen extends BaseCollectiveEconomySellHappen<CollectiveEconomySellHappen> {
	public static final CollectiveEconomySellHappen dao = new CollectiveEconomySellHappen();
	public static final String TABLE_NAME = "tb_collective_economy_sell_happen";
	/**
	 * @Description:保存集体经济收入信息
	 * @author Li Bangming;
	 * @date 2017年8月18日 下午3:38:41
	 * @collectiveEconomy 集体经济收入信息对象
	 * @return
	 */
	public  boolean saveCollectiveEconomySellHappen(CollectiveEconomySellHappen collectiveEconomySellHappen) {
	    boolean isSave=	collectiveEconomySellHappen.save();
		return isSave;
	}
	/**
	 * @Description:根据id查询集体经济收入信息
	 * @author Li Bangming;
	 * @date 2017年8月18日 下午3:38:41
	 * @collectiveEconomy 集体经济收入信息对象
	 * @return
	 */
	public  static  CollectiveEconomySellHappen queryCollectiveEconomySellHappenById(String id) {
		return dao.findById(id);
	}
	
	/**
	 * @Description:保存集体经济收入信息
	 * @author Li Bangming;
	 * @date 2017年8月18日 下午3:38:41
	 * @collectiveEconomy 集体经济收入信息对象
	 * @return
	 */
	public  boolean updateCollectiveEconomySellHappen(CollectiveEconomySellHappen collectiveEconomySellHappen) {
	    boolean isUpdate=collectiveEconomySellHappen.update();
		return isUpdate;
	}
	/**
	 * @Description:分页集体经济收入信息
	 * @author Li Bangming;
	 * @date 2017年8月18日 下午3:38:41
	 * @return
	 */
	public static Page<CollectiveEconomySellHappen>  pageCollectiveEconomySellHappen(int pageNumber,int pageSize,String collectiveEconomyId,String regionId){
		String select=" select tvpi.*,(select name from tb_enterprise te where te.id=tvpi.orgId) as orgName ";
		String sqlExceptSelect="   from "+TABLE_NAME+" tvpi where collectiveEconomyId like '"+collectiveEconomyId+"' or regionId  like '"+regionId+"' order by tvpi.createTime DESC ";
		return dao.paginate(pageNumber, pageSize, select, sqlExceptSelect);
	}
}
