package com.arnold.server.model;

import java.util.List;

import com.arnold.server.model.base.BaseCultivationIncome;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CultivationIncome extends BaseCultivationIncome<CultivationIncome> {
	public static final CultivationIncome dao = new CultivationIncome();
	
	/**
	 * 获取年度种植收入类型记录
	 * @param familyId
	 * @param searchYear
	 * @return
	 */
	public List<Record> getCultivationOrderInfos(String familyId,
			String searchYear) {
		String sql = "SELECT "
			+ " tci.familyId, "
			+ " tci.typeId, "
			+ " SUM(tci.area) AS `area`, "
			+ " CONVERT(SUM(tci.income),DECIMAL) AS income "
			+ " FROM "
			+ " tb_cultivation_income tci " 
			+ " WHERE tci.familyId = ? " 
			+ " AND tci.createTime LIKE '"+searchYear+"%' " 
			+ " GROUP BY tci.typeId";
		return Db.find(sql, familyId);
	}
	
	/**
	 * 获取家庭种殖收入
	 * @param pFamilyId
	 * @param year
	 * @return
	 */
	public double countCultivationIncomeByFamilyId(String pFamilyId, String year) {
		double resCome = 0d;
		String sql = " SELECT  "
				+ "   IFNULL(CONVERT(SUM(tci.income), DECIMAL), 0) as income "
				+ " FROM "
				+ "   tb_cultivation_income tci  "
				+ " WHERE tci.familyId = '"+pFamilyId+"'  "
				+ "   AND tci.createTime LIKE '"+year+"%'";
		Record info = Db.findFirst(sql);
		if(null!=info && null!=info.getBigDecimal("income")){
			resCome = info.getBigDecimal("income").doubleValue();
		}
		return resCome;
	}
	
}
