package com.arnold.server.model;

import java.util.List;

import com.arnold.server.model.base.BaseEducationParticipant;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;
import com.pallas.utils.Utils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EducationParticipant extends BaseEducationParticipant<EducationParticipant> {
	public static final EducationParticipant dao = new EducationParticipant();
	
	public Page<EducationParticipant> pageEducationParticipant(int pageNumber, int pageSize, String ids){
		
		String sql = "SELECT *";
		
		String sqlExceptSelect = " FROM tb_education_participant t1 WHERE 1=1 ";
		
		if(!Utils.isBlankOrEmpty(ids)){
			sqlExceptSelect += " AND t1.id IN (";
			String[] idArr = ids.split(",");
			for(String id : idArr){
				sqlExceptSelect += "'" + id + "',";
			}
			sqlExceptSelect = sqlExceptSelect.substring(0,sqlExceptSelect.length()-1)+")";
		}
		
		return dao.paginate(pageNumber, pageSize, sql, sqlExceptSelect);
				
	}
	
	public List<Record> pageEducationParticipantByEducationid(int pageNumber, int pageSize,
			String educationid) {
		String sql = "SELECT t1.*,m.name,v.`name`,v.sexId,v.birthday,v.IDnumber,f.phone,v.raceId, "+
					 "f.townid,f.hamletid,'是',v1.`name` as villagerName,f.phone,t1.joinMoneyType "+
					 "FROM tb_education_participant t1 "+
					 "LEFT JOIN tb_villager v ON v.id = t1.joinPersonid "+
					 "LEFT JOIN tb_member m ON m.id = t1.helpPersonid "+
					 "LEFT JOIN tb_family f ON v.familyId = f.id "+
					 "LEFT JOIN tb_villager v1 ON v1.id = f.villagerId WHERE 1=1 ";
		if(!Utils.isBlankOrEmpty(educationid)){
			sql += " AND t1.educationid = '" + educationid + "'";
		}
		
		sql +=" LIMIT "+(pageNumber-1)*pageSize+"," +pageSize;
		return Db.find(sql);
		
//		return dao.paginate(pageNumber, pageSize, sql, sqlExceptSelect);
	}

}
