package com.arnold.server.model;

import java.util.ArrayList;
import java.util.List;

import com.arnold.server.model.base.BaseEnterpriseMeasureRelation;
import com.huntersun.tool.Utils;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EnterpriseMeasureRelation extends BaseEnterpriseMeasureRelation<EnterpriseMeasureRelation> {
	public static final EnterpriseMeasureRelation dao = new EnterpriseMeasureRelation();
	
	private static final String tableName = "tb_enterprise_measure_relation";
	private static final String sqlSelectAll = "select * from " + tableName + " ";
		
	/**
	 * 
	 */
	public static EnterpriseMeasureRelation findFirstByEnterprise(String enterpriseId) {
		if(enterpriseId==null) return null;
		
		String sql = sqlSelectAll + "WHERE enterpriseId = ? and isValid=1";
		return dao.findFirst(sql, enterpriseId);
	}

	public EnterpriseMeasureRelation findBy(String enterpriseId, String measureId) {
		return dao.findFirst("select * from " + tableName + " where enterpriseId=? and measureId=? and isValid=?",
				enterpriseId, measureId, 1);
	}

	public Page<EnterpriseMeasureRelation> pageMeasure(String enterpriseId,String measureId, Integer pageNumber,
			Integer pageSize) {
		String selectSQL = "SELECT * ";
		String fromSQL = " FROM " + tableName;

		String whereSQL = "";
		List<Object> paras = new ArrayList<Object>();

		if (!Utils.isBlankOrEmpty(enterpriseId)) {
			if (Utils.isBlankOrEmpty(whereSQL)) {
				whereSQL = "WHERE";
			}
			whereSQL += " AND enterpriseId=?";
			paras.add(enterpriseId);
		}
		if (!Utils.isBlankOrEmpty(measureId)) {
			if (Utils.isBlankOrEmpty(whereSQL)) {
				whereSQL = "WHERE";
			}
			whereSQL += " AND measureId=?";
			paras.add(measureId);
		}

		String orderBy = " ORDER BY createTime DESC";
		return dao.paginate(pageNumber, pageSize, selectSQL, fromSQL + whereSQL + orderBy, paras.toArray());

	}
}
