package com.arnold.server.model;

import com.arnold.server.model.base.BaseEnterprise;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;
import com.pallas.utils.Utils;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Enterprise extends BaseEnterprise<Enterprise> {
	public static final Enterprise dao = new Enterprise();
	public static final String tableName = "tb_enterprise";

	public Page<Enterprise> pageEnterpriseByIds(int pageNumber, int pageSize, String ids){
		
		String sql = "SELECT *";
		String sqlExceptSelect = " FROM tb_enterprise t1 ";
		
		if(!Utils.isBlankOrEmpty(ids)){
			
			String[] idStrArr = ids.split(",");
			int i = 0;
			for(String str : idStrArr){
				if(i == 0){
					sqlExceptSelect += " WHERE t1.id = '" + str + "'";
				}else{
					sqlExceptSelect += " OR t1.id = '" + str + "'";
				}
				i++;
			}
			
		}
		
		return dao.paginate(pageNumber, pageSize, sql, sqlExceptSelect);
				
	}
	/**
	 * @Description: 查询企业列表
	 * @author Li Bangming;
	 * @date 2017年8月18日 下午4:22:15
	 * @return
	 */
	public static  List<Enterprise> queryAllEnterprises(){
		return dao.find("select * from "+tableName);
				
	}

	public Page<Record> pageEnterpriseByKeyWord(int pageNumber, int pageSize, String keyWord) {

		String sql = "SELECT e.*, SUM(p.number) AS zprs, COUNT(v1.id) AS llrs, COUNT(v2.id) AS bllrs ";

		String sqlExceptSelect = " FROM tb_enterprise e LEFT JOIN tb_post p ON e.id = p.orgId LEFT JOIN tb_villager_post_happen v1 " +
				"ON v1.postId = p.id AND v1.ralationType = 3 LEFT JOIN tb_villager_post_happen v2 ON v2.postId = p.id " +
				"AND v2.ralationType = 2 ";

		if(!Utils.isBlankOrEmpty(keyWord)){

			sqlExceptSelect+=" WHERE e.name LIKE '%"+keyWord+"%' ";

		}
		sqlExceptSelect+="  GROUP BY e.id  order by e.updateTime desc ";
		return Db.paginate(pageNumber, pageSize, sql, sqlExceptSelect);
	}
}
