package com.arnold.server.model;

import java.util.ArrayList;
import java.util.List;

import com.arnold.server.model.base.BaseFamilyConditionRelation;
import com.huntersun.tool.Utils;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FamilyConditionRelation extends BaseFamilyConditionRelation<FamilyConditionRelation> {
	public static final FamilyConditionRelation dao = new FamilyConditionRelation();

	public static final String TABLE_NAME = "tb_family_condition_relation";

	public FamilyConditionRelation findBy(String familyId, String conditionId) {
		return dao.findFirst("select * from " + TABLE_NAME + " where familyId=? and conditionId=? and isValid=?",
				familyId, conditionId, 1);
	}

	public Page<FamilyConditionRelation> pageFamilyConditionRelation(String familyId, String conditionId,
			Integer pageNumber, Integer pageSize) {
		String selectSQL = "SELECT * ";
		String fromSQL = " FROM " + TABLE_NAME;
		
		String whereSQL = "";
		List<Object> paras = new ArrayList<Object>();

		if (!Utils.isBlankOrEmpty(familyId)) {
			if (Utils.isBlankOrEmpty(whereSQL)) {
				whereSQL = "WHERE";
			}
			whereSQL += " AND familyId=?";
			paras.add(familyId);
		}
		if (!Utils.isBlankOrEmpty(conditionId)) {
			if (Utils.isBlankOrEmpty(whereSQL)) {
				whereSQL = "WHERE";
			}
			whereSQL += " AND conditionId=?";
			paras.add(conditionId);
		}

		String orderBy = " ORDER BY createTime DESC";
		return dao.paginate(pageNumber, pageSize, selectSQL, fromSQL + whereSQL + orderBy, paras.toArray());
	}

}
