package com.arnold.server.model;

import com.arnold.server.model.base.BaseFamilyProductioncondition;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FamilyProductioncondition extends BaseFamilyProductioncondition<FamilyProductioncondition> {
	public static final FamilyProductioncondition dao = new FamilyProductioncondition();
}
