package com.arnold.server.model;

import com.arnold.server.model.base.BaseFamilyPovertyHappen;
import com.arnold.server.util.ArnoldUtils;
import com.huntersun.tool.Utils;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FamilyPovertyHappen extends BaseFamilyPovertyHappen<FamilyPovertyHappen> {
	public static final FamilyPovertyHappen dao = new FamilyPovertyHappen();
	public static final String tableName = "tb_family_poverty_happen";
	
	/**
	 * @Description:保存贫困户脱贫流水表
	 * @author Li Bangming;
	 * @date 2017年8月12日 下午3:38:41
	 * @villagerPostIncome 贫困户脱贫流水表
	 * @return
	 */
	public  boolean saveFamilyPovertyHappen(FamilyPovertyHappen villagerPostIncome) {
	    boolean isSave=	villagerPostIncome.save();
		return isSave;
	}

	/**
	 * @Description:分页
	 * @author Li Bangming;
	 * @date 2017年8月12日 下午3:38:41
	 * @return
	 */
	public static Page<FamilyPovertyHappen> pageFamilyPovertyHappen(int pageNumber,int pageSize,String familyId,String ralationTypeId,String keyWord){
		String keyWordExpress=ArnoldUtils.EMPTY_STR;
		if(!Utils.isBlankOrEmpty(keyWord)){
			keyWord=ArnoldUtils.decodeSpecialChars(keyWord);
			keyWordExpress="  and  tvpi.familyId in(select tp.id from tb_post tp where tp.number like '%"+keyWord+"%')";
		}
		String select=" select tvpi.* ,(select tp.number from tb_family tp where tp.id=tvpi.familyId) as number";
		String sqlExceptSelect="   from " + tableName + " tvpi where familyId like '%" + familyId + "%' and  ralationTypeId like '%"+ralationTypeId+"%' "+keyWordExpress;
		return dao.paginate(pageNumber, pageSize, select, sqlExceptSelect,familyId,ralationTypeId);
	}

	/**
	 * @Author PanChangGui
	 * @Time 2017年10月5日 下午12:45:47
	 * @Description 
	 */
	public Page<FamilyPovertyHappen> pageFamilyPovertyPropertyRecord(String familyId, Integer pageNumber,
			Integer pageSize) {
		// TODO Auto-generated method stub
		
		String select="SELECT * ";
		String sqlExceptSelect=" FROM " + tableName + " WHERE familyId=? AND isValid>=? ORDER BY createTime DESC";
		return dao.paginate(pageNumber, pageSize, select, sqlExceptSelect,familyId,0);
	}
}
