package com.arnold.server.model;

import com.arnold.server.model.base.BaseFamilyStatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FamilyStatus extends BaseFamilyStatus<FamilyStatus> {
	public static final FamilyStatus dao = new FamilyStatus();
	
	public static final String TABLE_NAME = "tb_family_status";

	public FamilyStatus findByFamilyId(String familyId) {
		return dao.findFirst("select * from " + TABLE_NAME + " where familyId=? and isValid=?",
				familyId, 1);
	}
}
