package com.arnold.server.model;

import java.util.ArrayList;
import java.util.List;

import com.arnold.server.model.base.BaseFamilySoldierdepentantRelation;
import com.huntersun.tool.Utils;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FamilySoldierdepentantRelation extends BaseFamilySoldierdepentantRelation<FamilySoldierdepentantRelation> {
	public static final FamilySoldierdepentantRelation dao = new FamilySoldierdepentantRelation();
	public static final String TABLE_NAME = "tb_family_soldierdependent_relation";

	/**
	 * 
	 */
	public Page<FamilySoldierdepentantRelation> pageFamilySoldierdepentantRelation(String familyId, Integer pageNumber,
			Integer pageSize) {
		// TODO Auto-generated method stub
		return null;
	}

	public FamilySoldierdepentantRelation findBy(String familyId, String soldierDepentantId) {
		return dao.findFirst("select * from " + TABLE_NAME + " where familyId=? and soldierDepentantId=? and isValid>=?",
				familyId, soldierDepentantId, 0);
	}

	public Page<FamilySoldierdepentantRelation> pageSoldierDepentant(String familyId,String soldierDepentantId, Integer pageNumber,
			Integer pageSize) {
		String selectSQL = "SELECT * ";
		String fromSQL = " FROM " + TABLE_NAME;
		
		String whereSQL = "";
		List<Object> paras = new ArrayList<Object>();

		if (!Utils.isBlankOrEmpty(familyId)) {
			if (Utils.isBlankOrEmpty(whereSQL)) {
				whereSQL = "WHERE";
			}
			whereSQL += " AND familyId=?";
			paras.add(familyId);
		}
		if (!Utils.isBlankOrEmpty(soldierDepentantId)) {
			if (Utils.isBlankOrEmpty(whereSQL)) {
				whereSQL = "WHERE";
			}
			whereSQL += " AND soldierDepentantId=?";
			paras.add(soldierDepentantId);
		}

		String orderBy = " ORDER BY createTime DESC";
		return dao.paginate(pageNumber, pageSize, selectSQL, fromSQL + whereSQL + orderBy, paras.toArray());

	}
}
