package com.arnold.server.model;

import java.util.ArrayList;
import java.util.List;

import com.arnold.server.model.base.BaseFamilyBurdenRelation;
import com.huntersun.tool.Utils;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FamilyBurdenRelation extends BaseFamilyBurdenRelation<FamilyBurdenRelation> {
	public static final FamilyBurdenRelation dao = new FamilyBurdenRelation();

	private static final String tableName = "tb_family_burden_relation";

	
	public FamilyBurdenRelation findFirstByFamily(String familyId) {
		return dao.findFirst("select * from " + tableName + " where familyId=? and isValid >=?", familyId, 0);
	}

	public List<FamilyBurdenRelation> findAll() {
		return dao.find("select * from " + tableName);
	}
	
	public FamilyBurdenRelation findBy(String familyId, String burdenId) {
		return dao.findFirst("select * from " + tableName + " where familyId=? and burdenId=? and isValid >=?", familyId,
				burdenId, 0);
	}

	public Page<FamilyBurdenRelation> pageFamilyBurdenRelation(String familyId, String burdenId, Integer pageNumber,
			Integer pageSize) {
		/*String selectSQL = "SELECT * ";
		String fromSQL = " FROM " + tableName;

		String whereSQL = "";
		List<Object> paras = new ArrayList<Object>();

		if (!Utils.isBlankOrEmpty(familyId)) {
			if (Utils.isBlankOrEmpty(whereSQL)) {
				whereSQL = "WHERE";
			}
			whereSQL += " AND familyId=?";
			paras.add(familyId);
		}
		if (!Utils.isBlankOrEmpty(burdenId)) {
			if (Utils.isBlankOrEmpty(whereSQL)) {
				whereSQL = "WHERE";
			}
			whereSQL += " AND burdenId=?";
			paras.add(burdenId);
		}

		String sql = "SELECT * FROM ";
		String sqlExceptSelect = "";
		
		String orderBy = " ORDER BY createTime DESC";
		return dao.paginate(pageNumber, pageSize, selectSQL, fromSQL + whereSQL + orderBy, paras.toArray());*/
		
		return null;
	}
	
	
}
