package com.arnold.server.model;

import com.arnold.server.model.base.BaseFamilyEconomicSpecialSituationHappen;
import com.huntersun.tool.Utils;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FamilyEconomicSpecialSituationHappen extends BaseFamilyEconomicSpecialSituationHappen<FamilyEconomicSpecialSituationHappen> {
	public static final FamilyEconomicSpecialSituationHappen dao = new FamilyEconomicSpecialSituationHappen();
	public static final String TABLE_NAME = "tb_family_economic_special_situation_happen";
	/**
	 * @Description:保存家庭经济特殊情况信息
	 * @author Li Bangming;
	 * @date 2017年8月18日 下午3:38:41
	 * @collectiveEconomy 家庭经济特殊情况信息对象
	 * @return
	 */
	public  boolean saveFamilyEconomicSpecialSituationHappen(FamilyEconomicSpecialSituationHappen familyEconomicSpecialSituationHappen) {
	    boolean isSave=	familyEconomicSpecialSituationHappen.save();
		return isSave;
	}
	/**
	 * @Description:根据id查询家庭经济特殊情况信息
	 * @author Li Bangming;
	 * @date 2017年8月18日 下午3:38:41
	 * @collectiveEconomy 家庭经济特殊情况信息对象
	 * @return
	 */
	public  static  FamilyEconomicSpecialSituationHappen queryFamilyEconomicSpecialSituationHappenById(String id) {
		return dao.findById(id);
	}
	
	/**
	 * @Description:保存家庭经济特殊情况信息
	 * @author Li Bangming;
	 * @date 2017年8月18日 下午3:38:41
	 * @collectiveEconomy 家庭经济特殊情况信息对象
	 * @return
	 */
	public  boolean updateFamilyEconomicSpecialSituationHappen(FamilyEconomicSpecialSituationHappen familyEconomicSpecialSituationHappen) {
	    boolean isUpdate=familyEconomicSpecialSituationHappen.update();
		return isUpdate;
	}
	/**
	 * @Description:删除庭经济特殊情况信息
	 * @author Li Bangming;
	 * @date 2017年8月18日 下午3:38:41
	 * @collectiveEconomy 家庭经济特殊情况信息对象
	 * @return
	 */
	public  boolean deleteFamilyEconomicSpecialSituationHappen(FamilyEconomicSpecialSituationHappen familyEconomicSpecialSituationHappen) {
	    boolean isUpdate=familyEconomicSpecialSituationHappen.delete();
		return isUpdate;
	}
	/**
	 * @Description:分页家庭经济特殊情况信息
	 * @author Li Bangming;
	 * @date 2017年8月18日 下午3:38:41
	 * @return
	 */
	public static Page<FamilyEconomicSpecialSituationHappen>  pageFamilyEconomicSpecialSituationHappen(int pageNumber,int pageSize,
			String familyEconomicId,String familyId,String parentTypeId){
		String select=" select tvpi.* ";
		String sqlExceptSelect="   from "+TABLE_NAME+" tvpi  where familyId=?";
		if (!Utils.isBlankOrEmpty(parentTypeId)) {
			sqlExceptSelect += " and parentTypeId like'"+parentTypeId+"'";
		}
		return dao.paginate(pageNumber, pageSize, select, sqlExceptSelect,familyId);
	}
}
