package com.arnold.server.model;

import java.util.ArrayList;
import java.util.List;

import com.arnold.server.model.base.BaseFamilyInsuranceRelation;
import com.huntersun.tool.Utils;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FamilyInsuranceRelation extends BaseFamilyInsuranceRelation<FamilyInsuranceRelation> {
	public static final FamilyInsuranceRelation dao = new FamilyInsuranceRelation();

	public static final String tableName = "tb_family_insurance_relation";

	public Page<FamilyInsuranceRelation> pageFamilyInsuranceRelation(String familyId, String insuranceId, Integer pageNumber,
			Integer pageSize) {

		String selectSQL = "SELECT * ";
		String fromSQL = "FROM " + tableName + " ";

		String whereSQL = "";
		List<Object> paras = new ArrayList<Object>();

		if (!Utils.isBlankOrEmpty(familyId)) {
			if (Utils.isBlankOrEmpty(whereSQL)) {
				whereSQL = "WHERE";
			}
			whereSQL += " AND familyId=?";
			paras.add(familyId);
		}
		if (!Utils.isBlankOrEmpty(insuranceId)) {
			if (Utils.isBlankOrEmpty(whereSQL)) {
				whereSQL = "WHERE";
			}
			whereSQL += " AND insuranceId=?";
			paras.add(insuranceId);
		}

		String orderBy = " ORDER BY createTime DESC";
		return dao.paginate(pageNumber, pageSize, selectSQL, fromSQL + whereSQL + orderBy, paras.toArray());


	}

	public FamilyInsuranceRelation findBy(String familyId, String insuranceId) {
		String sql = "select * from " + tableName + " WHERE familyId =? and insuranceId=? and isValid>=?";
		return dao.findFirst(sql, familyId, insuranceId, 0);
	}
}
