package com.arnold.server.model;

import java.util.List;

import com.arnold.server.model.base.BaseFamilyShiftIncomeHappen;
import com.arnold.server.util.ArnoldUtils;
import com.huntersun.tool.Utils;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FamilyShiftIncomeHappen extends BaseFamilyShiftIncomeHappen<FamilyShiftIncomeHappen> {
	public static final FamilyShiftIncomeHappen dao = new FamilyShiftIncomeHappen();
	public static final String tableName = "tb_family_shift_income_happen";
	
	/**
	 * @Description:保存贫困户转移性收入
	 * @author Li Bangming;
	 * @date 2017年6月8日 下午3:38:41
	 * @villagerPostIncome 贫困户转移性收入对象
	 * @return
	 */
	public  boolean saveFamilyShiftIncomeHappen(FamilyShiftIncomeHappen villagerPostIncome) {
	    boolean isSave=	villagerPostIncome.save();
		return isSave;
	}

	/**
	 * @Description:分页
	 * @author Li Bangming;
	 * @date 2017年7月5日 下午3:38:41
	 * @return
	 */
	public static Page<FamilyShiftIncomeHappen>  pageFamilyShiftIncomeHappen(int pageNumber,int pageSize,String fmailyId,String keyWord){
		String keyWordExpress=ArnoldUtils.EMPTY_STR;
		if(!Utils.isBlankOrEmpty(keyWord)){
			keyWord=ArnoldUtils.decodeSpecialChars(keyWord);
			keyWordExpress=" where tvpi.postId in(select tp.id from tb_post tp where tp.name like '%"+keyWord+"%')";
		}
		String select=" select tvpi.* ,(select tp.name from tb_post tp where tp.id=tvpi.postId) as postName";
		String sqlExceptSelect="   from "+tableName+" tvpi "+keyWordExpress;
		return dao.paginate(pageNumber, pageSize, select, sqlExceptSelect);
	}
	
	/**
	 * 获取年度村民转移性类型收入
	 * @param familyId
	 * @param searchYear
	 * @return
	 */
	public List<Record> getShiftOrderInfos(String familyId, String searchYear) {
		String sql = "SELECT "
				+ "  tfsih.fmailyId, "
				+ "  tfsih.incomTypeId, "
				+ "  CONVERT(SUM(tfsih.income),DECIMAL) AS income "
				+ " FROM "
				+ "  tb_family_shift_income_happen tfsih "
				+ " WHERE tfsih.fmailyId = ? "
				+ "   AND tfsih.incomeTime LIKE '"+ searchYear +"%' "
				+ " GROUP BY tfsih.incomTypeId  ";
		return Db.find(sql, familyId);
	}
}
