package com.arnold.server.model;

import com.arnold.server.model.base.BaseFamilyWarningHappen;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FamilyWarningHappen extends BaseFamilyWarningHappen<FamilyWarningHappen> {
	public static final FamilyWarningHappen dao = new FamilyWarningHappen();
	
	final static String tableName = " tb_family_warning_happen";

	public Page<FamilyWarningHappen> pageFamilyWarnHappenByFId(Integer pageNumber,
			Integer pageSize, String familyId) {
		String select = "SELECT *";	
		String sqlExceptSelect =" FROM " + tableName + " where isValid>=0 and familyId=? ";
		return dao.paginate(pageNumber, pageSize, select, sqlExceptSelect, familyId);
	}
	
}
