package com.arnold.server.model;

import java.util.ArrayList;
import java.util.List;

import com.arnold.server.model.base.BaseHouseConditionRelation;
import com.huntersun.tool.Utils;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HouseConditionRelation extends BaseHouseConditionRelation<HouseConditionRelation> {
	public static final HouseConditionRelation dao = new HouseConditionRelation();
	public static final String TABLE_NAME = "tb_house_condition_relation";

	public HouseConditionRelation findBy(String houseId, String conditionId) {
		return dao.findFirst("select * from " + TABLE_NAME + " where houseId=? and conditionId=? and isValid=?",
				houseId, conditionId, 1);
	}

	public Page<HouseConditionRelation> pageHouseConditionRelation(String houseId, String conditionId, Integer pageNumber,
			Integer pageSize) {
		String selectSQL = "SELECT * ";
		String fromSQL = " FROM " + TABLE_NAME;
		
		String whereSQL = "";
		List<Object> paras = new ArrayList<Object>();

		if (!Utils.isBlankOrEmpty(houseId)) {
			if (Utils.isBlankOrEmpty(whereSQL)) {
				whereSQL = "WHERE";
			}
			whereSQL += " AND houseId=?";
			paras.add(houseId);
		}
		if (!Utils.isBlankOrEmpty(conditionId)) {
			if (Utils.isBlankOrEmpty(whereSQL)) {
				whereSQL = "WHERE";
			}
			whereSQL += " AND conditionId=?";
			paras.add(conditionId);
		}

		String orderBy = " ORDER BY createTime DESC";
		return dao.paginate(pageNumber, pageSize, selectSQL, fromSQL + whereSQL + orderBy, paras.toArray());
	}
}
