package com.arnold.server.model;

import com.arnold.server.model.base.BaseIndustry;
import com.arnold.server.util.ArnoldUtils;
import com.jfinal.plugin.activerecord.Page;
import com.pallas.utils.Utils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Industry extends BaseIndustry<Industry> {
	public static final Industry dao = new Industry();
	public static final String tableName = "tb_industry";

	public Page<Industry> pageIndustryByIds(int pageNumber, int pageSize, String ids){
		
		String sql = "SELECT *";
		
		String sqlExceptSelect = " FROM tb_industry t1 ";
		
		if(!Utils.isBlankOrEmpty(ids)){
			
			String[] idStrArr = ids.split(",");
			int i = 0;
			for(String str : idStrArr){
				if(i == 0){
					sqlExceptSelect += " WHERE t1.id = '" + str + "'";
				}else{
					sqlExceptSelect += " OR t1.id = '" + str + "'";
				}
				i++;
			}
			
		}
		
		return dao.paginate(pageNumber, pageSize, sql, sqlExceptSelect);
				
	}
	/**
	 * @Description: 根据产业类型id查询
	 * @author Li Bangming;
	 * @date 2017年8月17日 下午1:47:19
	 * @param typeId
	 * @return
	 */
	public static Industry queryIndustryByTypeId(String typeId){
		String sql="select * from "+tableName+" where typeId=?";
		return dao.findFirst(sql,typeId);
	}
	
	/**
	 * @Description: 分页查询价格日志
	 * @author Li Bangming;
	 * @date 2017年8月17日 下午3:06:30
	 * @param pageNumber
	 * @param pageSize
	 * @param ids
	 * @return
	 */
	public static Page<Industry> pageIndustryPrice(int pageNumber, int pageSize,String startDate, String endDate,  String keyWord){
		String whereExpress=ArnoldUtils.EMPTY_STR;
		if(!Utils.isBlankOrEmpty(keyWord)||startDate!=null||endDate!=null){
			whereExpress=" where ";
		}
		String startDateExpress=ArnoldUtils.EMPTY_STR;
		if(startDate!=null){
			startDateExpress=" UNIX_TIMESTAMP(operatorTime) >=unix_timestamp('"+startDate+"')";
		}
		String endDateExpress=ArnoldUtils.EMPTY_STR;
		if(endDate!=null){
			if(startDate==null){
				endDateExpress=" UNIX_TIMESTAMP(operatorTime) >=unix_timestamp('"+endDate+"')";
			}else{
				endDateExpress=" and UNIX_TIMESTAMP(operatorTime) >=unix_timestamp('"+endDate+"')";
			}
		}
		String keyWordExpress=ArnoldUtils.EMPTY_STR;
		if(!Utils.isBlankOrEmpty(keyWord)){
			if(startDate==null&&endDate==null){
				keyWordExpress=" guidePrice like '%"+keyWord+"%'";
			}else{
				keyWordExpress="and  guidePrice like '%"+keyWord+"%'";
			}
		}
		String sql = "SELECT *";
		String sqlExceptSelect = " FROM tb_industry t1 "+whereExpress+startDateExpress+endDateExpress+keyWordExpress;
		
		return dao.paginate(pageNumber, pageSize, sql, sqlExceptSelect);
				
	}
}
