package com.arnold.server.model;

import java.util.ArrayList;
import java.util.List;

import com.arnold.server.model.base.BaseLeaderDepartmentRelation;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LeaderDepartmentRelation extends BaseLeaderDepartmentRelation<LeaderDepartmentRelation> {
	public static final LeaderDepartmentRelation dao = new LeaderDepartmentRelation();
	private static final String tableName = "tb_leader_department_relation";
	private static final String sqlSelectAll = "select * from " + tableName + " ";

	/**
	 * 
	 */
	public static LeaderDepartmentRelation findFirstByLeader(String leaderId) {
		if (leaderId == null)
			return null;

		String sql = sqlSelectAll + "WHERE leaderId = ? and isValid=0";
		return dao.findFirst(sql, leaderId);
	}

	public static LeaderDepartmentRelation findBy(String leaderId, String subjectId) {
		return dao.findFirst(
				"select * from " + tableName + " where leaderId=? and subjectId=? and isValid=?",
				leaderId, subjectId, 0);
	}

	public Page<LeaderDepartmentRelation> pageLeaderDepartmentRelation(String leaderId, String departmentId, String subjectId,
			Integer pageNumber, Integer pageSize) {
		String selectSQL = "SELECT * ";
		String fromSQL = " FROM " + tableName;
		String whereSQL = " WHERE leaderId=?";
		List<Object> paras = new ArrayList<Object>();
		paras.add(leaderId);

		String orderBy = " ORDER BY createTime DESC";
		return dao.paginate(pageNumber, pageSize, selectSQL, fromSQL + whereSQL + orderBy, paras.toArray());
	}
}
