package com.arnold.server.model;

import java.util.List;

import com.arnold.server.model.base.BaseLeader;
import com.jfinal.plugin.activerecord.Page;
import com.pallas.utils.Utils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Leader extends BaseLeader<Leader> {
	public static final Leader dao = new Leader();
	final static String tableName = "tb_leader";
	
	public Page<Leader> pageLeaderByIds(int pageNumber, int pageSize, String ids){
		
		String sql = "SELECT *";
		
		String sqlExceptSelect = " FROM tb_leader t1 ";
		
		if(!Utils.isBlankOrEmpty(ids)){		
			String[] idStrArr = ids.split(",");
			int i = 0;
			for(String str : idStrArr){
				if(i == 0){
					sqlExceptSelect += " WHERE t1.id = '" + str + "'";
				}else{
					sqlExceptSelect += " OR t1.id = '" + str + "'";
				}
				i++;
			}		
		}
		
		return dao.paginate(pageNumber, pageSize, sql, sqlExceptSelect);				
	}

	public List<Leader> findAllLeader(String helperTypeId) {
		String sql = null;
		
		if(!Utils.isBlankOrEmpty(helperTypeId)) {
			sql = "select id, name, orgId, levelId from " + tableName + " where isValid>=? and helperTypeId=?";
			return dao.find(sql, 0, helperTypeId);
		}
			
		sql = "select id, name, orgId, levelId from " + tableName + " where isValid>=?";
		return dao.find(sql, 0);
	}
	

	public static List<Leader> findAllLeaders() {
		String sql = null;
		sql = "select * from " + tableName ;
		return dao.find(sql);
	}
	
	public static Leader findLeaderByPhone(String phone) {
		String sql = null;
		sql = "select * from " + tableName +" where phone=?";
		return dao.findFirst(sql,phone);
	}
}
