package com.arnold.server.model;

import java.util.ArrayList;
import java.util.List;

import com.arnold.server.model.base.BaseLeaderRegionRelation;
import com.huntersun.tool.Utils;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LeaderRegionRelation extends BaseLeaderRegionRelation<LeaderRegionRelation> {
	public static final LeaderRegionRelation dao = new LeaderRegionRelation();
	private static final String tableName = "tb_leader_region_relation";
	private static final String sqlSelectAll = "select * from " + tableName + " ";

	/**
	 * 
	 */
	public static LeaderRegionRelation findFirstByLeader(String leaderId) {
		if (leaderId == null)
			return null;

		String sql = sqlSelectAll + "WHERE leaderId = ? and isValid=1";
		return dao.findFirst(sql, leaderId);
	}

	public static LeaderRegionRelation findBy(String leaderId, String regionId, String groupId, String memberId) {
		return dao.findFirst(
				"select * from " + tableName
						+ " where leaderId=? and regionId=? and groupId=? and memberId=? and isValid=?",
				leaderId, regionId, groupId, memberId, 1);
	}

	public Page<LeaderRegionRelation> pageBy(String leaderId, String regionId, String groupId, String memberId,
			Integer pageNumber, Integer pageSize) {
		String selectSQL = "SELECT * ";
		String fromSQL = "FROM " + tableName + " ";

		String whereSQL = "";
		List<Object> paras = new ArrayList<Object>();

		if (!Utils.isBlankOrEmpty(leaderId)) {
			if (Utils.isBlankOrEmpty(whereSQL)) {
				whereSQL = "WHERE";
			}
			whereSQL += " AND leaderId=?";
			paras.add(leaderId);
		}
		if (!Utils.isBlankOrEmpty(regionId)) {
			if (Utils.isBlankOrEmpty(whereSQL)) {
				whereSQL = "WHERE";
			}
			whereSQL += " AND regionId=?";
			paras.add(regionId);
		}
		if (!Utils.isBlankOrEmpty(groupId)) {
			if (Utils.isBlankOrEmpty(whereSQL)) {
				whereSQL = "WHERE";
			}
			whereSQL += " AND groupId=?";
			paras.add(groupId);
		}
		if (!Utils.isBlankOrEmpty(memberId)) {
			if (Utils.isBlankOrEmpty(whereSQL)) {
				whereSQL = "WHERE";
			}
			whereSQL += " AND memberId=?";
			paras.add(memberId);
		}

		String orderBy = " ORDER BY createTime DESC";
		return dao.paginate(pageNumber, pageSize, selectSQL, fromSQL + whereSQL + orderBy, paras.toArray());
	}

	public LeaderRegionRelation findByLeaderAndRegion(String leaderId, String regionId) {
		
		String sql = "select * from " + tableName + " where leaderId=? and regionId=?";
		
		return dao.findFirst(sql, leaderId, regionId);
	}

	public List<LeaderRegionRelation> findByRegion(String regionId) {
		//添加确实的where
		String sql = "select * from " + tableName + " where regionId=? and isValid=?";
		
		return dao.find(sql, regionId, 0);
	}
}
