package com.arnold.server.model;

import com.arnold.server.model.base.BaseLocateVillageHappen;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LocateVillageHappen extends BaseLocateVillageHappen<LocateVillageHappen> {
	public static final LocateVillageHappen dao = new LocateVillageHappen();
	public static final String TABLE_NAME = "tb_locate_village";
	/**
	 * @Description:保存驻村点流水
	 * @author Li Bangming;
	 * @date 2017年8月18日 下午3:38:41
	 * @familyEconomic 驻村点流水对象
	 * @return
	 */
	public  boolean saveLocateVillageHappen(LocateVillageHappen familyEconomic) {
	    boolean isSave=	familyEconomic.save();
		return isSave;
	}
	/**
	 * @Description:删除驻村点流水
	 * @author Li Bangming;
	 * @date 2017年8月18日 下午3:38:41
	 * @familyEconomic 驻村点流水对象
	 * @return
	 */
	public  boolean deleteLocateVillageHappen(LocateVillageHappen familyEconomic) {
	    boolean isDelete=familyEconomic.delete();
		return isDelete;
	}
	/**
	 * @Description:根据id查询驻村点流水
	 * @author Li Bangming;
	 * @date 2017年8月18日 下午3:38:41
	 * @familyEconomic 驻村点流水对象
	 * @return
	 */
	public  static  LocateVillageHappen queryLocateVillageHappenById(String id) {
		return dao.findById(id);
	}
	
	/**
	 * @Description:分页驻村点流水
	 * @author Li Bangming;
	 * @date 2017年8月18日 下午3:38:41
	 * @return
	 */
	public static Page<LocateVillageHappen>  pageLocateVillageHappen(int pageNumber,int pageSize,String locateVillageId){
		String select=" select * ";
		String sqlExceptSelect="   from "+TABLE_NAME+" tvpi where tvpi.locateVillageId= "+locateVillageId;
		return dao.paginate(pageNumber, pageSize, select, sqlExceptSelect);
	}
}
