package com.arnold.server.model;

import com.arnold.server.model.base.BaseLocateVillage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LocateVillage extends BaseLocateVillage<LocateVillage> {
	public static final LocateVillage dao = new LocateVillage();
}
