package com.arnold.server.model;

import com.arnold.server.model.base.BaseMemberFamilyHappen;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberFamilyHappen extends BaseMemberFamilyHappen<MemberFamilyHappen> {
	public static final MemberFamilyHappen dao = new MemberFamilyHappen();
}
