package com.arnold.server.model;

import java.util.ArrayList;
import java.util.List;

import com.arnold.server.model.base.BaseMemberFamilyRelation;
import com.huntersun.tool.Utils;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberFamilyRelation extends BaseMemberFamilyRelation<MemberFamilyRelation> {
	public static final MemberFamilyRelation dao = new MemberFamilyRelation();

	public static final String TABLE_NAME = "tb_member_family_relation";

	public MemberFamilyRelation findBy(String familyId, String memberId) {
		return dao.findFirst("select * from " + TABLE_NAME + " where familyId=? and memberId=? and isValid>=?", familyId,
				memberId, 0);
	}

	public Page<MemberFamilyRelation> pageMemberFamilyRelation(String familyId, String memberId, Integer pageNumber,
			Integer pageSize) {
		String selectSQL = "SELECT * ";
		String fromSQL = " FROM " + TABLE_NAME;
		String whereSQL = "";
		List<Object> paras = new ArrayList<Object>();

		if (!Utils.isBlankOrEmpty(familyId)) {
			if (Utils.isBlankOrEmpty(whereSQL)) {
				whereSQL = "WHERE";
			}
			whereSQL += " AND familyId=?";
			paras.add(familyId);
		}
		if (!Utils.isBlankOrEmpty(memberId)) {
			if (Utils.isBlankOrEmpty(whereSQL)) {
				whereSQL = "WHERE";
			}
			whereSQL += " AND memberId=?";
			paras.add(memberId);
		}

		String orderBy = " ORDER BY createTime DESC";
		return dao.paginate(pageNumber, pageSize, selectSQL, fromSQL + whereSQL + orderBy, paras.toArray());
	}

}
