package com.arnold.server.model;

import java.util.Date;
import java.util.List;

import com.arnold.server.model.base.BaseMemberRegionRelation;
import com.huntersun.tool.Utils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberRegionRelation extends BaseMemberRegionRelation<MemberRegionRelation> {
	public static final MemberRegionRelation dao = new MemberRegionRelation();
	final String tableName="tb_member_region_relation";
	
	public MemberRegionRelation findByMemberAndRegion(String memberId, String regionId) {
		String sql = "select * from " + tableName + " where leaderId=? and regionId=? and isValid=?";
		
		return dao.findFirst(sql, memberId, regionId, 0);
	}

	public List<MemberRegionRelation> findByRegion(String regionId) {
		String sql = "select * from " + tableName + " where regionId=? and isValid=?";
		
		return dao.find(sql, regionId, 0);
	}
	
	/**
	 * 获取对应类型的区域扶贫关系记录
	 * @param regionId
	 * @param relationType
	 * @return
	 */
	public List<MemberRegionRelation> findByRegion(String regionId, int relationType) {
		String sql = "select * from " + tableName + " where regionId=? and isValid=? and relationType=? ";
		
		return dao.find(sql, regionId, 0, relationType);
	}
	
	/**
	 * 新增扶贫区域关系记录
	 * @param memberId
	 * @param regionId
	 * @param relationType
	 * @return
	 */
	public boolean saveRecord(String memberId,String regionId,int relationType){
		MemberRegionRelation saveInfo = new MemberRegionRelation();
		Date curDate = new Date();
		saveInfo.setId(Utils.create36UUID());
		saveInfo.setMemberId(memberId);
		saveInfo.setRegionId(regionId);
		saveInfo.setRelationType(relationType);
		saveInfo.setCreateTime(curDate);
		saveInfo.setUpdateTime(curDate);
		saveInfo.setIsValid(0);
		return saveInfo.save();	
	}
	
}
