package com.arnold.server.model;

import com.arnold.server.model.base.BaseMemberOrgHappen;
import com.arnold.server.util.ArnoldUtils;
import com.huntersun.tool.Utils;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberOrgHappen extends BaseMemberOrgHappen<MemberOrgHappen> {
	public static final MemberOrgHappen dao = new MemberOrgHappen();
	public static final String tableName = "tb_member_org_happen";
	
	/**
	 * @Description:保存人员组织机构流水
	 * @author Li Bangming;
	 * @date 2017年6月8日 下午3:38:41
	 * @villagerPostIncome 人员组织机构流水对象
	 * @return
	 */
	public  boolean saveMemberOrgHappen(MemberOrgHappen villagerPostIncome) {
	    boolean isSave=	villagerPostIncome.save();
		return isSave;
	}

	/**
	 * @Description:分页
	 * @author Li Bangming;
	 * @date 2017年7月5日 下午3:38:41
	 * @return
	 */
	public static Page<MemberOrgHappen>  pageMemberOrgHappen(int pageNumber,int pageSize,String memberId,String orgId,String posId,String ralationType,String keyWord){
		String keyWordExpress=ArnoldUtils.EMPTY_STR;
		if(!Utils.isBlankOrEmpty(keyWord)){
			keyWord=ArnoldUtils.decodeSpecialChars(keyWord);
			keyWordExpress=" where tvpi.postId in(select tp.id from tb_post tp where tp.name like '%"+keyWord+"%')";
		}
		String select=" select tvpi.* ,(select tp.name from tb_post tp where tp.id=tvpi.postId) as postName";
		String sqlExceptSelect="   from "+tableName+" tvpi "+keyWordExpress;
		return dao.paginate(pageNumber, pageSize, select, sqlExceptSelect);
	}
}
