package com.arnold.server.model;

import com.arnold.server.model.base.BasePovertyCount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PovertyCount extends BasePovertyCount<PovertyCount> {
	public static final PovertyCount dao = new PovertyCount();
}
