package com.arnold.server.model;

import java.util.ArrayList;
import java.util.List;

import com.arnold.server.model.base.BaseProjectRegionRelation;
import com.huntersun.tool.Utils;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectRegionRelation extends BaseProjectRegionRelation<ProjectRegionRelation> {
	public static final ProjectRegionRelation dao = new ProjectRegionRelation();
	private static final String tableName = "tb_project_region_relation";
	private static final String sqlSelectAll = "select * from " + tableName + " ";

	/**
	 * 
	 */
	public static ProjectRegionRelation findFirstByProject(String projectId) {
		if (projectId == null)
			return null;

		String sql = sqlSelectAll + "WHERE projectId = ? and isValid=1";
		return dao.findFirst(sql, projectId);
	}

	public static ProjectRegionRelation findBy(String projectId, String regionId) {
		return dao.findFirst("select * from " + tableName + " where projectId=? and regionId=? and isValid=?",
				projectId, regionId, 1);
	}

	public Page<ProjectRegionRelation> pageProjectRegionRelation(String projectId, String regionId, Integer pageNumber,
			Integer pageSize) {
		String selectSQL = "SELECT * ";
		String fromSQL = " FROM " + tableName;
		
		String whereSQL = "";
		List<Object> paras = new ArrayList<Object>();

		if (!Utils.isBlankOrEmpty(projectId)) {
			if (Utils.isBlankOrEmpty(whereSQL)) {
				whereSQL = "WHERE";
			}
			whereSQL += " AND projectId=?";
			paras.add(projectId);
		}
		if (!Utils.isBlankOrEmpty(regionId)) {
			if (Utils.isBlankOrEmpty(whereSQL)) {
				whereSQL = "WHERE";
			}
			whereSQL += " AND regionId=?";
			paras.add(regionId);
		}

		String orderBy = " ORDER BY createTime DESC";
		return dao.paginate(pageNumber, pageSize, selectSQL, fromSQL + whereSQL + orderBy, paras.toArray());
	}

}
