package com.arnold.server.model;

import com.arnold.server.model.base.BaseProjectInvestHappen;
import com.jfinal.plugin.activerecord.Page;
import com.pallas.utils.Utils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectInvestHappen extends BaseProjectInvestHappen<ProjectInvestHappen> {
	public static final ProjectInvestHappen dao = new ProjectInvestHappen();

	public Page<ProjectInvestHappen> pageProjectInvestByProjectid(int pageNumber, int pageSize,
			String projectid) {
		String sql = "SELECT *";
		String sqlExceptSelect = " FROM tb_project_invest_happen t1 ";
		if(!Utils.isBlankOrEmpty(projectid)){
			sqlExceptSelect += " WHERE t1.projectId = '" + projectid + "'";
		}
		return dao.paginate(pageNumber, pageSize, sql, sqlExceptSelect);
		
	}
	
	public Page<ProjectInvestHappen> pageProjectInvestByid(int pageNumber, int pageSize,
			String id){
		String sql = "SELECT * ";
		String sqlExceptSelect = " FROM tb_project_invest_happen t1 WHERE 1=1 ";
		if(!Utils.isBlankOrEmpty(id)){
			sqlExceptSelect += " AND t1.id = '" + id + "'";
		}
		return dao.paginate(pageNumber, pageSize, sql, sqlExceptSelect);
		
	}
}