package com.arnold.server.model;

import com.arnold.server.model.base.BasePublicServiceInvestHappen;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PublicServiceInvestHappen extends BasePublicServiceInvestHappen<PublicServiceInvestHappen> {
	public static final PublicServiceInvestHappen dao = new PublicServiceInvestHappen();
}
