package com.arnold.server.model;

import com.arnold.server.model.base.BaseProject;
import com.arnold.server.model.base.BasePublicService;
import com.jfinal.plugin.activerecord.Page;
import com.pallas.utils.Utils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PublicService extends BaseProject<PublicService> {
	public static final PublicService dao = new PublicService();

	public Page<PublicService> pagePublicServiceByIds(int pageNumber, int pageSize, String ids){
		
		String sql = "SELECT *";
		
		String sqlExceptSelect = " FROM tb_project t1 WHERE t1.type = 'public' ";
		
		if(!Utils.isBlankOrEmpty(ids)){
			sqlExceptSelect += " AND t3.id IN (";
			String[] idArr = ids.split(",");
			for(String id : idArr){
				sqlExceptSelect += "'" + id + "',";
			}
			sqlExceptSelect = sqlExceptSelect.substring(0,sqlExceptSelect.length()-1)+")";
		}
		
		return dao.paginate(pageNumber, pageSize, sql, sqlExceptSelect);
				
	}
	
}
