package com.arnold.server.model;

import java.util.List;

import com.arnold.server.model.base.BaseRegion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Region extends BaseRegion<Region> {
	public static final Region dao = new Region();

	final String tableName = "tb_region";
	
	public Region findByRegionId(String id) {
		// TODO Auto-generated method stub
		
		String sql = "select * from " + tableName + " where id=? and isValid=?";
			
		return dao.findFirst(sql, id, 0);
	}

	public List<Region> findRegion(int regionType) {
		// TODO Auto-generated method stub
		
		String sql = "select * from " + tableName + " where regionType=? and isValid=?";
		
		return dao.find(sql, regionType, 0);
	}

	public List<Region> findPovertyRegion(int regionType) {
		String sql = "select * from " + tableName + " where regionType=? and property=? and isValid>=?";
		
		return dao.find(sql, regionType, 0, 0);
	}

	public List<Region> findVillageNameList() {
		String sql = "select id,shortName,parentId,parentName,regionType from " + tableName + " where regionType=? and property=? and isValid=?";
		
		//regionType:节点等级；0根节点，1省，2市/州，3县，4乡/镇，5村，6组
		return dao.find(sql, 5, 0, 0);
	}

	public List<Region> findChildRegion(String parentId) {
		String sql = "select * from " + tableName + " where parentId=? and isValid=?";
		
		return dao.find(sql, parentId, 0);
	}
	
	public List<Region> findChildPovertyRegion(String parentId) {
		String sql = "select * from " + tableName + " where parentId=? and property=? and isValid=?";
		
		return dao.find(sql, parentId, 0, 0);
	}

	/**
	 * @Author PanChangGui
	 * @Email 823468425@qq.com
	 * @Time 2017年9月22日 下午2:51:02
	 * @Description 
	 */
	public List<Region> listAllRegion() {
		//String sql = "select * from " + tableName + " where isValid>=?";
		
		String sql = "SELECT * FROM "
					+ " (select *, case shortName "
					+ " when '一组'  then 1  "
					+ " when '二组'  then 2 "
					+ " when '三组'  then 3  "
					+ " when '四组'  then 4  "
					+ " when '五组'  then 5  "
					+ " when '六组'  then 6  "
					+ " when '七组'  then 7  "
					+ " when '八组'  then 8  "
					+ " when '九组'  then 9  "
					+ " when '十组'  then 10  "
					+ " when '十一组'  then 11  "
					+ " when '十二组'  then 12  "
					+ " else 0"
					+ " END  AS orderNo  "
					+ " from tb_region ) temp"
					+ " WHERE isValid>=?"
					+ " ORDER BY parentId asc, orderNo asc";
		
		return dao.find(sql, 0);
	}
	
	/**
	 * 获取乡拥有的组信息
	 * @param countryId
	 * @return
	 */
	public List<Region> findGroupInfoByCountryId(String countryId) {
		String sql = "SELECT tr.id FROM tb_region tr WHERE tr.isValid=0 AND tr.regionType=6 AND EXISTS ("
				+ "SELECT 1 FROM tb_region etr WHERE etr.isValid=tr.isValid AND etr.id=tr.parentId AND etr.parentId=?"
				+ ")";
		return dao.find(sql, countryId);
	}
}
