package com.arnold.server.model;

import com.arnold.server.model.base.BaseRegionInvestHappen;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RegionInvestHappen extends BaseRegionInvestHappen<RegionInvestHappen> {
	public static final RegionInvestHappen dao = new RegionInvestHappen();
	public static final String tableName = "tb_region_invest_happen";
	/**
	 * @Description:保存村投资流水表
	 * @author Li Bangming;
	 * @date 2017年8月12日 下午3:38:41
	 * @familyUnderwriterSellHappen 村投资流水表
	 * @return
	 */
	public static RegionInvestHappen findRegionInvestHappenById(String id) {
		return dao.findById(id);
	}
	/**
	 * @Description:查询村投资流水表
	 * @author Li Bangming;
	 * @date 2017年8月12日 下午3:38:41
	 * @familyUnderwriterSellHappen 村投资流水表
	 * @return
	 */
	public static RegionInvestHappen findRegionInvestHappenByProjectIdAndRegionIdAndYearAndMonth(String projectId, String regionId,int year, int month,String company) {
		String sql="select * from "+tableName+" where projectId=? and regionId=? and year=? and month=? and company=?";
		return dao.findFirst(sql,projectId,regionId, year,month,company);
	}
	/**
	 * @Description:保存村投资流水表
	 * @author Li Bangming;
	 * @date 2017年8月12日 下午3:38:41
	 * @familyUnderwriterSellHappen 村投资流水表
	 * @return
	 */
	public  boolean saveRegionInvestHappen(RegionInvestHappen familyUnderwriterSellHappen) {
	    boolean isSave=	familyUnderwriterSellHappen.save();
		return isSave;
	}
	/**
	 * @Description: 更新
	 * @author Li Bangming;
	 * @date 2017年8月12日 上午11:27:39
	 * @param familyUnderwriterSellHappen
	 * @return
	 */
	public  boolean updateRegionInvestHappen(RegionInvestHappen familyUnderwriterSellHappen) {
	    boolean isSave=	familyUnderwriterSellHappen.update();
		return isSave;
	}

	/**
	 * @Description:分页
	 * @author Li Bangming;
	 * @date 2017年8月12日 下午3:38:41
	 * @return
	 */
	public static Page<RegionInvestHappen>  pageRegionInvestHappen(int pageNumber,int pageSize,String projectId,String regionId ){
		String select=" select tvpi.* ,(select tp.number from tb_family tp where tp.id=tvpi.fmailyId) as number";
		String sqlExceptSelect="   from "+tableName+" tvpi where projectId like '%"+projectId+"%' and  regionId like '%"+regionId+"%' ";
		return dao.paginate(pageNumber, pageSize, select, sqlExceptSelect);
	}
}
