package com.arnold.server.model;

import com.arnold.server.model.base.BaseStatisticsPovertyIncome;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StatisticsPovertyIncome extends BaseStatisticsPovertyIncome<StatisticsPovertyIncome> {
	public static final StatisticsPovertyIncome dao = new StatisticsPovertyIncome();
}
