package com.arnold.server.model;

import com.arnold.server.model.base.BaseStatisticsPovertyReason;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StatisticsPovertyReason extends BaseStatisticsPovertyReason<StatisticsPovertyReason> {
	public static final StatisticsPovertyReason dao = new StatisticsPovertyReason();
}
