package com.arnold.server.model;

import com.arnold.server.model.base.BaseStatisticsPovertyEffect;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StatisticsPovertyEffect extends BaseStatisticsPovertyEffect<StatisticsPovertyEffect> {
	public static final StatisticsPovertyEffect dao = new StatisticsPovertyEffect();
}
