package com.arnold.server.model;

import com.arnold.server.model.base.BaseStatisticsProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StatisticsProject extends BaseStatisticsProject<StatisticsProject> {
	public static final StatisticsProject dao = new StatisticsProject();
}
