package com.arnold.server.model;

import com.arnold.server.model.base.BaseTeamHelp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TeamHelp extends BaseTeamHelp<TeamHelp> {
	public static final TeamHelp dao = new TeamHelp();
}
