package com.arnold.server.model;

import com.arnold.server.model.base.BaseTeamInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TeamInfo extends BaseTeamInfo<TeamInfo> {
	public static final TeamInfo dao = new TeamInfo();
}
