package com.arnold.server.model;

import com.arnold.server.model.base.BaseTeamInfoDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TeamInfoDetail extends BaseTeamInfoDetail<TeamInfoDetail> {
	public static final TeamInfoDetail dao = new TeamInfoDetail();
}
