package com.arnold.server.model;

import java.util.List;

import com.arnold.server.model.base.BaseTrain;
import com.arnold.server.model.base.BaseTrainParticipant;
import com.arnold.server.model.base.BaseTrainSpeaker;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;
import com.pallas.utils.Utils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TrainParticipant extends BaseTrainParticipant<TrainParticipant> {
	public static final TrainParticipant dao = new TrainParticipant();
	
	public Page<TrainParticipant> pageTrainParticipant(int pageNumber, int pageSize, String ids){
		
		String sql = "SELECT *";
		
		String sqlExceptSelect = " FROM tb_train_participant t1 WHERE 1=1 ";
		
		if(!Utils.isBlankOrEmpty(ids)){
			sqlExceptSelect += " AND t1.id IN (";
			String[] idArr = ids.split(",");
			for(String id : idArr){
				sqlExceptSelect += "'" + id + "',";
			}
			sqlExceptSelect = sqlExceptSelect.substring(0,sqlExceptSelect.length()-1)+")";
		}
		
		return dao.paginate(pageNumber, pageSize, sql, sqlExceptSelect);
				
	}
	
	public List<Record> pageTrainParticipantByTrainid(int pageNumber, int pageSize, String trainid) {
		
		String sql = "SELECT t1.*,m.`name` as mName,v.`name`,v.sexId,v.birthday,v.IDnumber,f.phone,v.raceId, "+
				 "f.townid,f.hamletid,'是',v1.`name` as villagerName,f.phone,t1.joinMoneyType "+
				 "FROM tb_train_participant t1 "+
				 "LEFT JOIN tb_villager v ON v.id = t1.joinPersonid "+
				 "LEFT JOIN tb_member m ON m.id = t1.helpPersonid "+
				 "LEFT JOIN tb_family f ON v.familyId = f.id "+
				 "LEFT JOIN tb_villager v1 ON v1.id = f.villagerId WHERE 1=1 ";
		if(!Utils.isBlankOrEmpty(trainid)){
			sql += " AND t1.trainid = '" + trainid + "'";
		}
		
		sql +=" LIMIT "+(pageNumber-1)*pageSize+"," +pageSize;
		return Db.find(sql);
	}

}
