package com.arnold.server.model;

import com.arnold.server.model.base.BaseValigerEduHappen;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ValigerEduHappen extends BaseValigerEduHappen<ValigerEduHappen> {
	public static final ValigerEduHappen dao = new ValigerEduHappen();
	public static final String tableName = "tb_valiger_edu_happen";

	/**
	 * @Description:保存村名教育流水
	 * @author Li Bangming;
	 * @date 2017年8月12日 下午3:38:41
	 * @familyUnderwriterSellHappen 村名教育流水
	 * @return
	 */
	public static ValigerEduHappen findValigerEduHappenById(String id) {
		return dao.findById(id);
	}
	/**
	 * @Description:保存村名教育流水
	 * @author Li Bangming;
	 * @date 2017年8月12日 下午3:38:41
	 * @familyUnderwriterSellHappen 村名教育流水
	 * @return
	 */
	public  boolean saveValigerEduHappen(ValigerEduHappen familyUnderwriterSellHappen) {
	    boolean isSave=	familyUnderwriterSellHappen.save();
		return isSave;
	}
	/**
	 * @Description: 更新
	 * @author Li Bangming;
	 * @date 2017年8月12日 上午11:27:39
	 * @param familyUnderwriterSellHappen
	 * @return
	 */
	public  boolean updateValigerEduHappen(ValigerEduHappen familyUnderwriterSellHappen) {
	    boolean isSave=	familyUnderwriterSellHappen.update();
		return isSave;
	}

	/**
	 * @Description:分页
	 * @author Li Bangming;
	 * @date 2017年8月12日 下午3:38:41
	 * @return
	 */
	public static Page<ValigerEduHappen>  pageValigerEduHappen(int pageNumber,int pageSize,String valigerId,String eduId,int ralationType){
		
		String select=" select tvpi.* ) as number";
		String sqlExceptSelect="   from "+tableName+" tvpi where valigerId like '%"+valigerId+"%' and  eduId  like '%"+eduId+"%' and ralationType=?";
		return dao.paginate(pageNumber, pageSize, select, sqlExceptSelect,ralationType);
	}
}
