package com.arnold.server.model;

import com.arnold.server.model.base.BaseValigerTrainHappen;
import com.arnold.server.util.ArnoldUtils;
import com.huntersun.tool.Utils;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ValigerTrainHappen extends BaseValigerTrainHappen<ValigerTrainHappen> {
	public static final ValigerTrainHappen dao = new ValigerTrainHappen();
	public static final String tableName = "tb_region_invest_happen";
	/**
	 * @Description:保存村名培训流水
	 * @author Li Bangming;
	 * @date 2017年8月12日 下午3:38:41
	 * @familyUnderwriterSellHappen 村名培训流水
	 * @return
	 */
	public static ValigerTrainHappen findValigerTrainHappenById(String id) {
		return dao.findById(id);
	}
	/**
	 * @Description:保存村名培训流水
	 * @author Li Bangming;
	 * @date 2017年8月12日 下午3:38:41
	 * @familyUnderwriterSellHappen 村名培训流水
	 * @return
	 */
	public  boolean saveValigerTrainHappen(ValigerTrainHappen familyUnderwriterSellHappen) {
	    boolean isSave=	familyUnderwriterSellHappen.save();
		return isSave;
	}
	/**
	 * @Description: 更新
	 * @author Li Bangming;
	 * @date 2017年8月12日 上午11:27:39
	 * @param familyUnderwriterSellHappen
	 * @return
	 */
	public  boolean updateValigerTrainHappen(ValigerTrainHappen familyUnderwriterSellHappen) {
	    boolean isSave=	familyUnderwriterSellHappen.update();
		return isSave;
	}

	/**
	 * @Description:分页
	 * @author Li Bangming;
	 * @date 2017年8月12日 下午3:38:41
	 * @return
	 */
	public static Page<ValigerTrainHappen>  pageValigerTrainHappen(int pageNumber,int pageSize,String valigerId,String trainId,int ralationType){
		String select=" select tvpi.* ,(select tp.number from tb_family tp where tp.id=tvpi.fmailyId) as number";
		String sqlExceptSelect="   from "+tableName+" tvpi where valigerId like '%"+valigerId+"%' and  trainId like '%"+trainId+"%' and ralationType=?";
		return dao.paginate(pageNumber, pageSize, select, sqlExceptSelect,ralationType);
	}
}
