package com.arnold.server.model;

import java.util.Date;

import com.arnold.server.model.base.BaseVillagerPostHappenBak;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VillagerPostHappenBak extends BaseVillagerPostHappenBak<VillagerPostHappenBak> {
	public static final VillagerPostHappenBak dao = new VillagerPostHappenBak();

	public boolean saveBak(VillagerPostHappen historyInfo) {
		VillagerPostHappenBak bakInfo = new VillagerPostHappenBak();
		bakInfo.setDelDate(new Date());//删除时间记录
		
		//bak
		bakInfo.setId(historyInfo.getId());
		bakInfo.setVillagerId(historyInfo.getVillagerId());
		bakInfo.setPostId(historyInfo.getPostId());
		bakInfo.setMemberId(historyInfo.getMemberId());
		bakInfo.setRalationType(historyInfo.getRalationType());
		bakInfo.setReason(historyInfo.getReason());
		bakInfo.setSalary(historyInfo.getSalary());
		bakInfo.setCreateUserId(historyInfo.getCreateUserId());
		bakInfo.setPostLeaveDate(historyInfo.getPostLeaveDate());
		bakInfo.setCreateTime(historyInfo.getCreateTime());
		bakInfo.setJobCategory(historyInfo.getJobCategory());
		bakInfo.setCompanyProject(historyInfo.getCompanyProject());
		bakInfo.setAverageIncome(historyInfo.getAverageIncome());
		bakInfo.setDepartment(historyInfo.getDepartment());
		bakInfo.setIsFiveFund(historyInfo.getIsFiveFund());
		bakInfo.setIsEatEncase(historyInfo.getIsEatEncase());
		bakInfo.setIsEat(historyInfo.getIsEat());
		bakInfo.setIsEncase(historyInfo.getIsEncase());
		bakInfo.setIsLunch(historyInfo.getIsLunch());
		bakInfo.setIsOther(historyInfo.getIsOther());
		bakInfo.setEditUserId(historyInfo.getEditUserId());
		bakInfo.setEditDate(historyInfo.getEditDate());
		bakInfo.setJobAddress(historyInfo.getJobAddress());
		
		return bakInfo.save();
	}
}
