package com.arnold.server.model;

import java.util.List;

import com.arnold.server.model.base.BaseVillagerPostIncomeHappen;
import com.arnold.server.util.ArnoldUtils;
import com.huntersun.tool.Utils;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VillagerPostIncomeHappen extends BaseVillagerPostIncomeHappen<VillagerPostIncomeHappen> {
	public static final VillagerPostIncomeHappen dao = new VillagerPostIncomeHappen();
	public static final String tableName = "tb_villager_post_income_happen";
	
	/**
	 * @Description:保存村名收入
	 * @author Li Bangming;
	 * @date 2017年6月8日 下午3:38:41
	 * @villagerPostIncome 村名收入对象
	 * @return
	 */
	public  boolean saveVillagerPostIncomeHappen(VillagerPostIncomeHappen villagerPostIncome) {
	    boolean isSave=	villagerPostIncome.save();
		return isSave;
	}

	/**
	 * @Description:分页
	 * @author Li Bangming;
	 * @date 2017年7月5日 下午3:38:41
	 * @return
	 */
	public static Page<VillagerPostIncomeHappen>  pageVillagerPostIncomeHappen(int pageNumber,int pageSize,String villagerId,String postId,String keyWord){
		String keyWordExpress=ArnoldUtils.EMPTY_STR;
		if(!Utils.isBlankOrEmpty(keyWord)){
			keyWord=ArnoldUtils.decodeSpecialChars(keyWord);
			keyWordExpress=" where tvpi.postId in(select tp.id from tb_post tp where tp.name like '%"+keyWord+"%')";
		}
		String select=" select tvpi.* ,(select tp.name from tb_post tp where tp.id=tvpi.postId) as postName";
		String sqlExceptSelect="   from "+tableName+" tvpi "+keyWordExpress;
		return dao.paginate(pageNumber, pageSize, select, sqlExceptSelect);
	}

	/**
	 * 获取家庭工资性年收入(取消)
	 * @param str
	 */
	/*public double countYearSalaryByFamilyId(String pFamilyId, String year) {
		double resCome = 0d;
		String sql = " SELECT  "
				+ "   IFNULL( "
				+ "     CONVERT(SUM(tvpih.income), DECIMAL), "
				+ "     0 "
				+ "   ) as income"
				+ " FROM "
				+ "   tb_villager_post_income_happen tvpih  "
				+ " WHERE tvpih.incomeTime LIKE '" + year +"%' "
				+ "   AND EXISTS  "
				+ "   (SELECT  "
				+ "     1  "
				+ "   FROM "
				+ "     tb_villager tv  "
				+ "   WHERE tv.id = tvpih.villagerId  "
				+ "     AND tv.familyId = '"+pFamilyId+"' "
				+ "     AND tv.isValid = 0) ";
		Record info = Db.findFirst(sql);
		if(null!=info && null!=info.getBigDecimal("income")){
			resCome = info.getBigDecimal("income").doubleValue();
		}
		return resCome;
	}*/
	
}
