package com.arnold.server.model;

import java.util.ArrayList;
import java.util.List;

import com.arnold.server.model.base.BaseVillagerPostRelation;
import com.huntersun.tool.Utils;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VillagerPostRelation extends BaseVillagerPostRelation<VillagerPostRelation> {
	public static final VillagerPostRelation dao = new VillagerPostRelation();
	
	public static final String TABLE_NAME = "tb_villager_postId_relation";

	public VillagerPostRelation findBy(String villagerId, String postId) {
		return dao.findFirst("select * from " + TABLE_NAME + " where villagerId=? and postId=? and isValid=?",
				villagerId, postId, 1);
	}

	public Page<VillagerPostRelation> pageVillagerPostRelation(String villagerId, String postId, Integer pageNumber,
			Integer pageSize) {
		String selectSQL = "SELECT * ";
		String fromSQL = " FROM " + TABLE_NAME;
		
		String whereSQL = "";
		List<Object> paras = new ArrayList<Object>();

		if (!Utils.isBlankOrEmpty(villagerId)) {
			if (Utils.isBlankOrEmpty(whereSQL)) {
				whereSQL = "WHERE";
			}
			whereSQL += " AND villagerId=?";
			paras.add(villagerId);
		}
		if (!Utils.isBlankOrEmpty(postId)) {
			if (Utils.isBlankOrEmpty(whereSQL)) {
				whereSQL = "WHERE";
			}
			whereSQL += " AND postId=?";
			paras.add(postId);
		}

		String orderBy = " ORDER BY createTime DESC";
		return dao.paginate(pageNumber, pageSize, selectSQL, fromSQL + whereSQL + orderBy, paras.toArray());
	}
}
