package com.arnold.server.model;

import com.arnold.server.model.base.BaseVisitCount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VisitCount extends BaseVisitCount<VisitCount> {
	public static final VisitCount dao = new VisitCount();
	
}
