package com.ares.server.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("tb_account", "id", Account.class);
		arp.addMapping("tb_account_balance", "id", AccountBalance.class);
		arp.addMapping("tb_account_channel", "id", AccountChannel.class);
		arp.addMapping("tb_account_update", "id", AccountUpdate.class);
		arp.addMapping("tb_flow", "id", Flow.class);
		arp.addMapping("tb_flow_detail", "id", FlowDetail.class);
		arp.addMapping("tb_flow_freeze", "id", FlowFreeze.class);
	}
}

