package com.ares.server.model;

import java.util.List;

import com.ares.server.model.base.BaseAccountBalance;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AccountBalance extends BaseAccountBalance<AccountBalance> {
	public static final AccountBalance dao = new AccountBalance();

	public static final String TABLE_NAME = "tb_account_balance";
	
	public static AccountBalance findByBalanceType(String account, Integer balanceType) {
		return dao.findFirst("select * from " + TABLE_NAME + " where accountId=? and type=?",
				account, balanceType);
	}

	public static List<AccountBalance> findByAccount(String account) {
		return dao.find("select * from " + TABLE_NAME + " where accountId=?", account);
	}
}
