package com.ares.server.model;

import com.ares.server.model.base.BaseAccountUpdate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AccountUpdate extends BaseAccountUpdate<AccountUpdate> {
	public static final AccountUpdate dao = new AccountUpdate();
	
	public static final String TABLE_NAME = "tb_account_update";
}
