package com.ares.server.model;

import com.ares.server.model.base.BaseFlowDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FlowDetail extends BaseFlowDetail<FlowDetail> {
	public static final FlowDetail dao = new FlowDetail();
	
	public static final String TABLE_NAME = "tb_flow_detail";
}
