package com.ares.server.model;

import com.ares.server.model.base.BaseFlowFreeze;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FlowFreeze extends BaseFlowFreeze<FlowFreeze> {
	public static final FlowFreeze dao = new FlowFreeze();
	
	public static final String TABLE_NAME = "tb_flow_freeze";
}
