package com.ares.server.model;

import java.util.List;

import com.ares.server.model.base.BaseFlow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Flow extends BaseFlow<Flow> {
	public static final Flow dao = new Flow();

	public static final String TABLE_NAME = "tb_flow";

	public static Flow findByOrderId(String orderId) {
		return dao.findFirst("select * from " + TABLE_NAME + " where orderId=?", orderId);
	}

	public static List<Flow> findByAccountIdAndBalanceType(String accountId, Integer balanceType) {
		return dao.find("select * from " + TABLE_NAME + " where accountId=? and balanceType=?", accountId, balanceType);
	}
	
	public static List<Flow> findByAccountIdAndChannelType(String accountId, Integer channelType) {
		return dao.find("select * from " + TABLE_NAME + " where accountId=? and channelType=?", accountId, channelType);
	}

}
