package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePost<M extends BasePost<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setTypeId(java.lang.String typeId) {
		set("typeId", typeId);
	}

	public java.lang.String getTypeId() {
		return get("typeId");
	}

	public void setOrgId(java.lang.String orgId) {
		set("orgId", orgId);
	}

	public java.lang.String getOrgId() {
		return get("orgId");
	}

	public void setNumber(java.lang.Integer number) {
		set("number", number);
	}

	public java.lang.Integer getNumber() {
		return get("number");
	}

	public void setAverageIncome(java.lang.Double averageIncome) {
		set("averageIncome", averageIncome);
	}

	public java.lang.Double getAverageIncome() {
		return get("averageIncome");
	}

	public void setDepartment(java.lang.String department) {
		set("department", department);
	}

	public java.lang.String getDepartment() {
		return get("department");
	}

	public void setBenefits(java.lang.String benefits) {
		set("benefits", benefits);
	}

	public java.lang.String getBenefits() {
		return get("benefits");
	}

	public void setIsFiveFund(java.lang.Integer isFiveFund) {
		set("isFiveFund", isFiveFund);
	}

	public java.lang.Integer getIsFiveFund() {
		return get("isFiveFund");
	}

	public void setIsEatEncase(java.lang.Integer isEatEncase) {
		set("isEatEncase", isEatEncase);
	}

	public java.lang.Integer getIsEatEncase() {
		return get("isEatEncase");
	}

	public void setIsEat(java.lang.Integer isEat) {
		set("isEat", isEat);
	}

	public java.lang.Integer getIsEat() {
		return get("isEat");
	}

	public void setIsEncase(java.lang.Integer isEncase) {
		set("isEncase", isEncase);
	}

	public java.lang.Integer getIsEncase() {
		return get("isEncase");
	}

	public void setIsLunch(java.lang.Integer isLunch) {
		set("isLunch", isLunch);
	}

	public java.lang.Integer getIsLunch() {
		return get("isLunch");
	}

	public void setIsOther(java.lang.Integer isOther) {
		set("isOther", isOther);
	}

	public java.lang.Integer getIsOther() {
		return get("isOther");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setWriterId(java.lang.String writerId) {
		set("writerId", writerId);
	}

	public java.lang.String getWriterId() {
		return get("writerId");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setOperatorId(java.lang.String operatorId) {
		set("operatorId", operatorId);
	}

	public java.lang.String getOperatorId() {
		return get("operatorId");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setAttachment(java.lang.String attachment) {
		set("attachment", attachment);
	}

	public java.lang.String getAttachment() {
		return get("attachment");
	}

}
