package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFamilyStatus<M extends BaseFamilyStatus<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setFamilyId(java.lang.String familyId) {
		set("familyId", familyId);
	}

	public java.lang.String getFamilyId() {
		return get("familyId");
	}

	public void setPovertyReason(java.lang.String povertyReason) {
		set("povertyReason", povertyReason);
	}

	public java.lang.String getPovertyReason() {
		return get("povertyReason");
	}

	public void setPovertyStatus(java.lang.String povertyStatus) {
		set("povertyStatus", povertyStatus);
	}

	public java.lang.String getPovertyStatus() {
		return get("povertyStatus");
	}

	public void setArticleId(java.lang.String articleId) {
		set("articleId", articleId);
	}

	public java.lang.String getArticleId() {
		return get("articleId");
	}

	public void setCreaterId(java.lang.String createrId) {
		set("createrId", createrId);
	}

	public java.lang.String getCreaterId() {
		return get("createrId");
	}

	public void setAuditorId(java.lang.String auditorId) {
		set("auditorId", auditorId);
	}

	public java.lang.String getAuditorId() {
		return get("auditorId");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
