package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTrain<M extends BaseTrain<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setTypeId(java.lang.String typeId) {
		set("typeId", typeId);
	}

	public java.lang.String getTypeId() {
		return get("typeId");
	}

	public void setPostId(java.lang.String postId) {
		set("postId", postId);
	}

	public java.lang.String getPostId() {
		return get("postId");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setPrice(java.lang.Double price) {
		set("price", price);
	}

	public java.lang.Double getPrice() {
		return get("price");
	}

	public void setFinalMoney(java.lang.Double finalMoney) {
		set("finalMoney", finalMoney);
	}

	public java.lang.Double getFinalMoney() {
		return get("finalMoney");
	}

	public void setStartTime(java.util.Date startTime) {
		set("startTime", startTime);
	}

	public java.util.Date getStartTime() {
		return get("startTime");
	}

	public void setEndTime(java.util.Date endTime) {
		set("endTime", endTime);
	}

	public java.util.Date getEndTime() {
		return get("endTime");
	}

	public void setOrgId(java.lang.String orgId) {
		set("orgId", orgId);
	}

	public java.lang.String getOrgId() {
		return get("orgId");
	}

	public void setCount(java.lang.Integer count) {
		set("count", count);
	}

	public java.lang.Integer getCount() {
		return get("count");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}

	public java.lang.String getUserId() {
		return get("userId");
	}

	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}

	public java.lang.String getWriter() {
		return get("writer");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setNowWriter(java.lang.String nowWriter) {
		set("nowWriter", nowWriter);
	}

	public java.lang.String getNowWriter() {
		return get("nowWriter");
	}

	public void setNowCreateTime(java.util.Date nowCreateTime) {
		set("nowCreateTime", nowCreateTime);
	}

	public java.util.Date getNowCreateTime() {
		return get("nowCreateTime");
	}

	public void setSkillTypeId(java.lang.String skillTypeId) {
		set("skillTypeId", skillTypeId);
	}

	public java.lang.String getSkillTypeId() {
		return get("skillTypeId");
	}

	public void setRealStartTime(java.util.Date realStartTime) {
		set("realStartTime", realStartTime);
	}

	public java.util.Date getRealStartTime() {
		return get("realStartTime");
	}

	public void setRealEndTime(java.util.Date realEndTime) {
		set("realEndTime", realEndTime);
	}

	public java.util.Date getRealEndTime() {
		return get("realEndTime");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("isValid");
	}

}
