package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVillager<M extends BaseVillager<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setSexId(java.lang.String sexId) {
		set("sexId", sexId);
	}

	public java.lang.String getSexId() {
		return get("sexId");
	}

	public void setIDnumber(java.lang.String IDnumber) {
		set("IDnumber", IDnumber);
	}

	public java.lang.String getIDnumber() {
		return get("IDnumber");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}

	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setRaceId(java.lang.String raceId) {
		set("raceId", raceId);
	}

	public java.lang.String getRaceId() {
		return get("raceId");
	}

	public void setIsTrain(java.lang.Integer isTrain) {
		set("isTrain", isTrain);
	}

	public java.lang.Integer getIsTrain() {
		return get("isTrain");
	}

	public void setFamilyId(java.lang.String familyId) {
		set("familyId", familyId);
	}

	public java.lang.String getFamilyId() {
		return get("familyId");
	}

	public void setRelationOfHouseholderId(java.lang.String relationOfHouseholderId) {
		set("relationOfHouseholderId", relationOfHouseholderId);
	}

	public java.lang.String getRelationOfHouseholderId() {
		return get("relationOfHouseholderId");
	}

	public void setIsWorking(java.lang.Integer isWorking) {
		set("isWorking", isWorking);
	}

	public java.lang.Integer getIsWorking() {
		return get("isWorking");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("isValid");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setEducationalId(java.lang.String educationalId) {
		set("educationalId", educationalId);
	}

	public java.lang.String getEducationalId() {
		return get("educationalId");
	}

	public void setHealthConditionId(java.lang.String healthConditionId) {
		set("healthConditionId", healthConditionId);
	}

	public java.lang.String getHealthConditionId() {
		return get("healthConditionId");
	}

	public void setMaritalStatusId(java.lang.String maritalStatusId) {
		set("maritalStatusId", maritalStatusId);
	}

	public java.lang.String getMaritalStatusId() {
		return get("maritalStatusId");
	}

	public void setIsSeriousPatient(java.lang.Integer isSeriousPatient) {
		set("isSeriousPatient", isSeriousPatient);
	}

	public java.lang.Integer getIsSeriousPatient() {
		return get("isSeriousPatient");
	}

	public void setLaborCapacityId(java.lang.String laborCapacityId) {
		set("laborCapacityId", laborCapacityId);
	}

	public java.lang.String getLaborCapacityId() {
		return get("laborCapacityId");
	}

	public void setSchoolStatusId(java.lang.String schoolStatusId) {
		set("schoolStatusId", schoolStatusId);
	}

	public java.lang.String getSchoolStatusId() {
		return get("schoolStatusId");
	}

	public void setLaborStatusId(java.lang.String laborStatusId) {
		set("laborStatusId", laborStatusId);
	}

	public java.lang.String getLaborStatusId() {
		return get("laborStatusId");
	}

	public void setLaborTimeId(java.lang.String laborTimeId) {
		set("laborTimeId", laborTimeId);
	}

	public java.lang.String getLaborTimeId() {
		return get("laborTimeId");
	}

	public void setInOutStatusId(java.lang.String inOutStatusId) {
		set("inOutStatusId", inOutStatusId);
	}

	public java.lang.String getInOutStatusId() {
		return get("inOutStatusId");
	}

	public void setIsWishEmployment(java.lang.Integer isWishEmployment) {
		set("isWishEmployment", isWishEmployment);
	}

	public java.lang.Integer getIsWishEmployment() {
		return get("isWishEmployment");
	}

	public void setExpectProfessionId(java.lang.String expectProfessionId) {
		set("expectProfessionId", expectProfessionId);
	}

	public java.lang.String getExpectProfessionId() {
		return get("expectProfessionId");
	}

	public void setExpectWorkplaceId(java.lang.String expectWorkplaceId) {
		set("expectWorkplaceId", expectWorkplaceId);
	}

	public java.lang.String getExpectWorkplaceId() {
		return get("expectWorkplaceId");
	}

	public void setIsWishTrain(java.lang.Integer isWishTrain) {
		set("isWishTrain", isWishTrain);
	}

	public java.lang.Integer getIsWishTrain() {
		return get("isWishTrain");
	}

	public void setExpectTrainProfessionId(java.lang.String expectTrainProfessionId) {
		set("expectTrainProfessionId", expectTrainProfessionId);
	}

	public java.lang.String getExpectTrainProfessionId() {
		return get("expectTrainProfessionId");
	}

	public void setExpectTrainTime(java.util.Date expectTrainTime) {
		set("expectTrainTime", expectTrainTime);
	}

	public java.util.Date getExpectTrainTime() {
		return get("expectTrainTime");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setSoldiersDependentsId(java.lang.String soldiersDependentsId) {
		set("soldiersDependentsId", soldiersDependentsId);
	}

	public java.lang.String getSoldiersDependentsId() {
		return get("soldiersDependentsId");
	}

	public void setInsuranceId(java.lang.String insuranceId) {
		set("insuranceId", insuranceId);
	}

	public java.lang.String getInsuranceId() {
		return get("insuranceId");
	}

	public void setMedicalInsuranceId(java.lang.String medicalInsuranceId) {
		set("medicalInsuranceId", medicalInsuranceId);
	}

	public java.lang.String getMedicalInsuranceId() {
		return get("medicalInsuranceId");
	}

	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}

	public java.lang.String getWriter() {
		return get("writer");
	}

	public void setOperator(java.lang.String operator) {
		set("operator", operator);
	}

	public java.lang.String getOperator() {
		return get("operator");
	}

	public void setAddReason(java.lang.String addReason) {
		set("addReason", addReason);
	}

	public java.lang.String getAddReason() {
		return get("addReason");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

}
