package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBreedIncome<M extends BaseBreedIncome<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setTypeId(java.lang.String typeId) {
		set("typeId", typeId);
	}

	public java.lang.String getTypeId() {
		return get("typeId");
	}

	public void setFamilyId(java.lang.String familyId) {
		set("familyId", familyId);
	}

	public java.lang.String getFamilyId() {
		return get("familyId");
	}

	public void setNumber(java.lang.Integer number) {
		set("number", number);
	}

	public java.lang.Integer getNumber() {
		return get("number");
	}

	public void setOrderBuy(java.lang.Integer orderBuy) {
		set("orderBuy", orderBuy);
	}

	public java.lang.Integer getOrderBuy() {
		return get("orderBuy");
	}

	public void setAlreadyBuy(java.lang.Integer alreadyBuy) {
		set("alreadyBuy", alreadyBuy);
	}

	public java.lang.Integer getAlreadyBuy() {
		return get("alreadyBuy");
	}

	public void setIncome(java.math.BigDecimal income) {
		set("income", income);
	}

	public java.math.BigDecimal getIncome() {
		return get("income");
	}

	public void setOperator(java.lang.String operator) {
		set("operator", operator);
	}

	public java.lang.String getOperator() {
		return get("operator");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
