package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVillagerPostHappen<M extends BaseVillagerPostHappen<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setVillagerId(java.lang.String villagerId) {
		set("villagerId", villagerId);
	}

	public java.lang.String getVillagerId() {
		return get("villagerId");
	}

	public void setPostId(java.lang.String postId) {
		set("postId", postId);
	}

	public java.lang.String getPostId() {
		return get("postId");
	}

	public void setMemberId(java.lang.String memberId) {
		set("memberId", memberId);
	}

	public java.lang.String getMemberId() {
		return get("memberId");
	}

	public void setRalationType(java.lang.Integer ralationType) {
		set("ralationType", ralationType);
	}

	public java.lang.Integer getRalationType() {
		return get("ralationType");
	}

	public void setReason(java.lang.String reason) {
		set("reason", reason);
	}

	public java.lang.String getReason() {
		return get("reason");
	}

	public void setSalary(java.lang.Double salary) {
		set("salary", salary);
	}

	public java.lang.Double getSalary() {
		return get("salary");
	}

	public void setCreateUserId(java.lang.String createUserId) {
		set("createUserId", createUserId);
	}

	public java.lang.String getCreateUserId() {
		return get("createUserId");
	}

	public void setPostLeaveDate(java.util.Date postLeaveDate) {
		set("postLeaveDate", postLeaveDate);
	}

	public java.util.Date getPostLeaveDate() {
		return get("postLeaveDate");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setJobCategory(java.lang.String jobCategory) {
		set("jobCategory", jobCategory);
	}

	public java.lang.String getJobCategory() {
		return get("jobCategory");
	}

	public void setCompanyProject(java.lang.String companyProject) {
		set("companyProject", companyProject);
	}

	public java.lang.String getCompanyProject() {
		return get("companyProject");
	}

	public void setAverageIncome(java.lang.Double averageIncome) {
		set("averageIncome", averageIncome);
	}

	public java.lang.Double getAverageIncome() {
		return get("averageIncome");
	}

	public void setDepartment(java.lang.String department) {
		set("department", department);
	}

	public java.lang.String getDepartment() {
		return get("department");
	}

	public void setIsFiveFund(java.lang.Integer isFiveFund) {
		set("isFiveFund", isFiveFund);
	}

	public java.lang.Integer getIsFiveFund() {
		return get("isFiveFund");
	}

	public void setIsEatEncase(java.lang.Integer isEatEncase) {
		set("isEatEncase", isEatEncase);
	}

	public java.lang.Integer getIsEatEncase() {
		return get("isEatEncase");
	}

	public void setIsEat(java.lang.Integer isEat) {
		set("isEat", isEat);
	}

	public java.lang.Integer getIsEat() {
		return get("isEat");
	}

	public void setIsEncase(java.lang.Integer isEncase) {
		set("isEncase", isEncase);
	}

	public java.lang.Integer getIsEncase() {
		return get("isEncase");
	}

	public void setIsLunch(java.lang.Integer isLunch) {
		set("isLunch", isLunch);
	}

	public java.lang.Integer getIsLunch() {
		return get("isLunch");
	}

	public void setIsOther(java.lang.Integer isOther) {
		set("isOther", isOther);
	}

	public java.lang.Integer getIsOther() {
		return get("isOther");
	}

	public void setEditUserId(java.lang.String editUserId) {
		set("editUserId", editUserId);
	}

	public java.lang.String getEditUserId() {
		return get("editUserId");
	}

	public void setEditDate(java.util.Date editDate) {
		set("editDate", editDate);
	}

	public java.util.Date getEditDate() {
		return get("editDate");
	}

	public void setJobAddress(java.lang.String jobAddress) {
		set("jobAddress", jobAddress);
	}

	public java.lang.String getJobAddress() {
		return get("jobAddress");
	}

}
