package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEducationParticipant<M extends BaseEducationParticipant<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setEducationid(java.lang.String educationid) {
		set("educationid", educationid);
	}

	public java.lang.String getEducationid() {
		return get("educationid");
	}

	public void setJoinPersonid(java.lang.String joinPersonid) {
		set("joinPersonid", joinPersonid);
	}

	public java.lang.String getJoinPersonid() {
		return get("joinPersonid");
	}

	public void setHelpPersonid(java.lang.String helpPersonid) {
		set("helpPersonid", helpPersonid);
	}

	public java.lang.String getHelpPersonid() {
		return get("helpPersonid");
	}

	public void setJoinMoneyType(java.lang.String joinMoneyType) {
		set("joinMoneyType", joinMoneyType);
	}
	
	public java.lang.String getJoinMoneyType() {
		return get("joinMoneyType");
	}

	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}

	public java.lang.String getWriter() {
		return get("writer");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setNowWriter(java.lang.String nowWriter) {
		set("nowWriter", nowWriter);
	}

	public java.lang.String getNowWriter() {
		return get("nowWriter");
	}

	public void setNowCreateTime(java.util.Date nowCreateTime) {
		set("nowCreateTime", nowCreateTime);
	}

	public java.util.Date getNowCreateTime() {
		return get("nowCreateTime");
	}

}
