package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFamilyEconomicHerds<M extends BaseFamilyEconomicHerds<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setFamilyEconomicId(java.lang.String familyEconomicId) {
		set("familyEconomicId", familyEconomicId);
	}

	public java.lang.String getFamilyEconomicId() {
		return get("familyEconomicId");
	}

	public void setFamilyId(java.lang.String familyId) {
		set("familyId", familyId);
	}

	public java.lang.String getFamilyId() {
		return get("familyId");
	}

	public void setTypeId(java.lang.String typeId) {
		set("typeId", typeId);
	}

	public java.lang.String getTypeId() {
		return get("typeId");
	}

	public void setAmount(java.lang.Integer amount) {
		set("amount", amount);
	}

	public java.lang.Integer getAmount() {
		return get("amount");
	}

	public void setPupsAmount(java.lang.Integer pupsAmount) {
		set("pupsAmount", pupsAmount);
	}

	public java.lang.Integer getPupsAmount() {
		return get("pupsAmount");
	}

	public void setAdultsAmount(java.lang.Integer adultsAmount) {
		set("adultsAmount", adultsAmount);
	}

	public java.lang.Integer getAdultsAmount() {
		return get("adultsAmount");
	}

	public void setMalesAmount(java.lang.Integer malesAmount) {
		set("malesAmount", malesAmount);
	}

	public java.lang.Integer getMalesAmount() {
		return get("malesAmount");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setOperatorId(java.lang.String operatorId) {
		set("operatorId", operatorId);
	}

	public java.lang.String getOperatorId() {
		return get("operatorId");
	}

	public void setOperatorTime(java.util.Date operatorTime) {
		set("operatorTime", operatorTime);
	}

	public java.util.Date getOperatorTime() {
		return get("operatorTime");
	}

}
