package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseValigerTrainHappen<M extends BaseValigerTrainHappen<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setValigerId(java.lang.String valigerId) {
		set("valigerId", valigerId);
	}

	public java.lang.String getValigerId() {
		return get("valigerId");
	}

	public void setMemberId(java.lang.String memberId) {
		set("memberId", memberId);
	}

	public java.lang.String getMemberId() {
		return get("memberId");
	}

	public void setTrainId(java.lang.String trainId) {
		set("trainId", trainId);
	}

	public java.lang.String getTrainId() {
		return get("trainId");
	}

	public void setRalationType(java.lang.Integer ralationType) {
		set("ralationType", ralationType);
	}

	public java.lang.Integer getRalationType() {
		return get("ralationType");
	}

	public void setTrainTime(java.util.Date trainTime) {
		set("trainTime", trainTime);
	}

	public java.util.Date getTrainTime() {
		return get("trainTime");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("createUser", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("createUser");
	}

}
