package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRegionInvestHappen<M extends BaseRegionInvestHappen<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setProjectId(java.lang.String projectId) {
		set("projectId", projectId);
	}

	public java.lang.String getProjectId() {
		return get("projectId");
	}

	public void setRegionId(java.lang.String regionId) {
		set("regionId", regionId);
	}

	public java.lang.String getRegionId() {
		return get("regionId");
	}

	public void setYear(java.lang.Integer year) {
		set("year", year);
	}

	public java.lang.Integer getYear() {
		return get("year");
	}

	public void setMonth(java.lang.Integer month) {
		set("month", month);
	}

	public java.lang.Integer getMonth() {
		return get("month");
	}

	public void setCompany(java.lang.String company) {
		set("company", company);
	}

	public java.lang.String getCompany() {
		return get("company");
	}

	public void setInvestPrice(java.lang.Double investPrice) {
		set("investPrice", investPrice);
	}

	public java.lang.Double getInvestPrice() {
		return get("investPrice");
	}

	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}

	public java.lang.String getWriter() {
		return get("writer");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setOperator(java.lang.String operator) {
		set("operator", operator);
	}

	public java.lang.String getOperator() {
		return get("operator");
	}

	public void setOperatorTime(java.util.Date operatorTime) {
		set("operatorTime", operatorTime);
	}

	public java.util.Date getOperatorTime() {
		return get("operatorTime");
	}

}
