package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLocateVillageHappen<M extends BaseLocateVillageHappen<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setLocateVillageId(java.lang.String locateVillageId) {
		set("locateVillageId", locateVillageId);
	}

	public java.lang.String getLocateVillageId() {
		return get("locateVillageId");
	}

	public void setPeopleNum(java.lang.Integer peopleNum) {
		set("peopleNum", peopleNum);
	}

	public java.lang.Integer getPeopleNum() {
		return get("peopleNum");
	}

	public void setPartyNum(java.lang.Integer partyNum) {
		set("partyNum", partyNum);
	}

	public java.lang.Integer getPartyNum() {
		return get("partyNum");
	}

	public void setPovertyOccurrence(java.lang.String povertyOccurrence) {
		set("povertyOccurrence", povertyOccurrence);
	}

	public java.lang.String getPovertyOccurrence() {
		return get("povertyOccurrence");
	}

	public void setInfirmNum(java.lang.Integer infirmNum) {
		set("infirmNum", infirmNum);
	}

	public java.lang.Integer getInfirmNum() {
		return get("infirmNum");
	}

	public void setPovertyNum(java.lang.Integer povertyNum) {
		set("povertyNum", povertyNum);
	}

	public java.lang.Integer getPovertyNum() {
		return get("povertyNum");
	}

	public void setProtectNum(java.lang.Integer protectNum) {
		set("protectNum", protectNum);
	}

	public java.lang.Integer getProtectNum() {
		return get("protectNum");
	}

	public void setYearPlan(java.lang.String yearPlan) {
		set("yearPlan", yearPlan);
	}

	public java.lang.String getYearPlan() {
		return get("yearPlan");
	}

	public void setDangerousHouse(java.lang.String dangerousHouse) {
		set("dangerousHouse", dangerousHouse);
	}

	public java.lang.String getDangerousHouse() {
		return get("dangerousHouse");
	}

	public void setTapWater(java.lang.String tapWater) {
		set("tapWater", tapWater);
	}

	public java.lang.String getTapWater() {
		return get("tapWater");
	}

	public void setRoadHarde(java.lang.String roadHarde) {
		set("roadHarde", roadHarde);
	}

	public java.lang.String getRoadHarde() {
		return get("roadHarde");
	}

	public void setTreatedPersonnel(java.lang.String treatedPersonnel) {
		set("treatedPersonnel", treatedPersonnel);
	}

	public java.lang.String getTreatedPersonnel() {
		return get("treatedPersonnel");
	}

	public void setGroupRoad(java.lang.String groupRoad) {
		set("groupRoad", groupRoad);
	}

	public java.lang.String getGroupRoad() {
		return get("groupRoad");
	}

	public void setHavePrimarySchool(java.lang.String havePrimarySchool) {
		set("havePrimarySchool", havePrimarySchool);
	}

	public java.lang.String getHavePrimarySchool() {
		return get("havePrimarySchool");
	}

	public void setOutSchoolChildrenNum(java.lang.Integer outSchoolChildrenNum) {
		set("outSchoolChildrenNum", outSchoolChildrenNum);
	}

	public java.lang.Integer getOutSchoolChildrenNum() {
		return get("outSchoolChildrenNum");
	}

	public void setLastYearAverage(java.lang.String lastYearAverage) {
		set("lastYearAverage", lastYearAverage);
	}

	public java.lang.String getLastYearAverage() {
		return get("lastYearAverage");
	}

	public void setCollectiveEconomyScale(java.lang.String collectiveEconomyScale) {
		set("collectiveEconomyScale", collectiveEconomyScale);
	}

	public java.lang.String getCollectiveEconomyScale() {
		return get("collectiveEconomyScale");
	}

	public void setPerArableLand(java.lang.String perArableLand) {
		set("perArableLand", perArableLand);
	}

	public java.lang.String getPerArableLand() {
		return get("perArableLand");
	}

	public void setPerLand(java.lang.String perLand) {
		set("perLand", perLand);
	}

	public java.lang.String getPerLand() {
		return get("perLand");
	}

	public void setMainProblems(java.lang.String mainProblems) {
		set("mainProblems", mainProblems);
	}

	public java.lang.String getMainProblems() {
		return get("mainProblems");
	}

	public void setOperatorId(java.lang.String operatorId) {
		set("operatorId", operatorId);
	}

	public java.lang.String getOperatorId() {
		return get("operatorId");
	}

	public void setOperateTime(java.util.Date operateTime) {
		set("operateTime", operateTime);
	}

	public java.util.Date getOperateTime() {
		return get("operateTime");
	}

}
