package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFamilyLivecondition<M extends BaseFamilyLivecondition<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setFamilyId(java.lang.String familyId) {
		set("familyId", familyId);
	}

	public java.lang.String getFamilyId() {
		return get("familyId");
	}

	public void setCultivatedArea(java.lang.String cultivatedArea) {
		set("cultivatedArea", cultivatedArea);
	}

	public java.lang.String getCultivatedArea() {
		return get("cultivatedArea");
	}

	public void setEffectiveIrrigationArea(java.lang.String effectiveIrrigationArea) {
		set("effectiveIrrigationArea", effectiveIrrigationArea);
	}

	public java.lang.String getEffectiveIrrigationArea() {
		return get("effectiveIrrigationArea");
	}

	public void setField(java.lang.String field) {
		set("field", field);
	}

	public java.lang.String getField() {
		return get("field");
	}

	public void setLand(java.lang.String land) {
		set("land", land);
	}

	public java.lang.String getLand() {
		return get("land");
	}

	public void setForestryArea(java.lang.String forestryArea) {
		set("forestryArea", forestryArea);
	}

	public java.lang.String getForestryArea() {
		return get("forestryArea");
	}

	public void setBackForestryArea(java.lang.String backForestryArea) {
		set("backForestryArea", backForestryArea);
	}

	public java.lang.String getBackForestryArea() {
		return get("backForestryArea");
	}

	public void setFruitTreeArea(java.lang.String fruitTreeArea) {
		set("fruitTreeArea", fruitTreeArea);
	}

	public java.lang.String getFruitTreeArea() {
		return get("fruitTreeArea");
	}

	public void setGrassArea(java.lang.String grassArea) {
		set("grassArea", grassArea);
	}

	public java.lang.String getGrassArea() {
		return get("grassArea");
	}

	public void setWaterArea(java.lang.String waterArea) {
		set("waterArea", waterArea);
	}

	public java.lang.String getWaterArea() {
		return get("waterArea");
	}

	public void setEconomicArea(java.lang.String economicArea) {
		set("economicArea", economicArea);
	}

	public java.lang.String getEconomicArea() {
		return get("economicArea");
	}

	public void setIsDrinkDifficulty(java.lang.Integer isDrinkDifficulty) {
		set("isDrinkDifficulty", isDrinkDifficulty);
	}

	public java.lang.Integer getIsDrinkDifficulty() {
		return get("isDrinkDifficulty");
	}

	public void setIsDrinkSafety(java.lang.Integer isDrinkSafety) {
		set("isDrinkSafety", isDrinkSafety);
	}

	public java.lang.Integer getIsDrinkSafety() {
		return get("isDrinkSafety");
	}

	public void setDrinkConditionId(java.lang.String drinkConditionId) {
		set("drinkConditionId", drinkConditionId);
	}

	public java.lang.String getDrinkConditionId() {
		return get("drinkConditionId");
	}

	public void setIsGalvanical(java.lang.Integer isGalvanical) {
		set("isGalvanical", isGalvanical);
	}

	public java.lang.Integer getIsGalvanical() {
		return get("isGalvanical");
	}

	public void setIsTelevision(java.lang.Integer isTelevision) {
		set("isTelevision", isTelevision);
	}

	public java.lang.Integer getIsTelevision() {
		return get("isTelevision");
	}

	public void setConsumerGoodsCondition(java.lang.String consumerGoodsCondition) {
		set("consumerGoodsCondition", consumerGoodsCondition);
	}

	public java.lang.String getConsumerGoodsCondition() {
		return get("consumerGoodsCondition");
	}

	public void setTrunklineDistance(java.lang.String trunklineDistance) {
		set("trunklineDistance", trunklineDistance);
	}

	public java.lang.String getTrunklineDistance() {
		return get("trunklineDistance");
	}

	public void setNearestMarketDistance(java.lang.String nearestMarketDistance) {
		set("nearestMarketDistance", nearestMarketDistance);
	}

	public java.lang.String getNearestMarketDistance() {
		return get("nearestMarketDistance");
	}

	public void setRegisterRoadTypeId(java.lang.String registerRoadTypeId) {
		set("registerRoadTypeId", registerRoadTypeId);
	}

	public java.lang.String getRegisterRoadTypeId() {
		return get("registerRoadTypeId");
	}

	public void setRoadCondition(java.lang.Integer roadCondition) {
		set("roadCondition", roadCondition);
	}

	public java.lang.Integer getRoadCondition() {
		return get("roadCondition");
	}

	public void setBuildHouseYear(java.lang.String buildHouseYear) {
		set("buildHouseYear", buildHouseYear);
	}

	public java.lang.String getBuildHouseYear() {
		return get("buildHouseYear");
	}

	public void setHousingArea(java.lang.String housingArea) {
		set("housingArea", housingArea);
	}

	public java.lang.String getHousingArea() {
		return get("housingArea");
	}

	public void setHasHouse(java.lang.Integer hasHouse) {
		set("hasHouse", hasHouse);
	}

	public java.lang.Integer getHasHouse() {
		return get("hasHouse");
	}

	public void setHouseStructureId(java.lang.String houseStructureId) {
		set("houseStructureId", houseStructureId);
	}

	public java.lang.String getHouseStructureId() {
		return get("houseStructureId");
	}

	public void setIsDangerousBuilding(java.lang.Integer isDangerousBuilding) {
		set("isDangerousBuilding", isDangerousBuilding);
	}

	public java.lang.Integer getIsDangerousBuilding() {
		return get("isDangerousBuilding");
	}

	public void setFuelsTypeId(java.lang.String fuelsTypeId) {
		set("fuelsTypeId", fuelsTypeId);
	}

	public java.lang.String getFuelsTypeId() {
		return get("fuelsTypeId");
	}

	public void setIsSanitaryToilet(java.lang.Integer isSanitaryToilet) {
		set("isSanitaryToilet", isSanitaryToilet);
	}

	public java.lang.Integer getIsSanitaryToilet() {
		return get("isSanitaryToilet");
	}

	public void setProductionArea(java.lang.String productionArea) {
		set("productionArea", productionArea);
	}

	public java.lang.String getProductionArea() {
		return get("productionArea");
	}

	public void setLiveArea(java.lang.String liveArea) {
		set("liveArea", liveArea);
	}

	public java.lang.String getLiveArea() {
		return get("liveArea");
	}

	public void setLongitude(java.lang.String longitude) {
		set("longitude", longitude);
	}

	public java.lang.String getLongitude() {
		return get("longitude");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setOperator(java.lang.String operator) {
		set("operator", operator);
	}

	public java.lang.String getOperator() {
		return get("operator");
	}

	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}

	public java.lang.String getWriter() {
		return get("writer");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("isValid");
	}

	public void setLatitude(java.lang.String latitude) {
		set("latitude", latitude);
	}

	public java.lang.String getLatitude() {
		return get("latitude");
	}

	public void setHeight(java.lang.String height) {
		set("height", height);
	}

	public java.lang.String getHeight() {
		return get("height");
	}

	public void setOutstandingLoan(java.lang.String outstandingLoan) {
		set("outstandingLoan", outstandingLoan);
	}

	public java.lang.String getOutstandingLoan() {
		return get("outstandingLoan");
	}

	public void setOperatingIncome(java.lang.String operatingIncome) {
		set("operatingIncome", operatingIncome);
	}

	public java.lang.String getOperatingIncome() {
		return get("operatingIncome");
	}

	public void setReceivedLowGold(java.lang.String receivedLowGold) {
		set("receivedLowGold", receivedLowGold);
	}

	public java.lang.String getReceivedLowGold() {
		return get("receivedLowGold");
	}

	public void setPerCapitaIncome(java.lang.String perCapitaIncome) {
		set("perCapitaIncome", perCapitaIncome);
	}

	public java.lang.String getPerCapitaIncome() {
		return get("perCapitaIncome");
	}

	public void setAnnualNetIncome(java.lang.String annualNetIncome) {
		set("annualNetIncome", annualNetIncome);
	}

	public java.lang.String getAnnualNetIncome() {
		return get("annualNetIncome");
	}

	public void setAnnualIncome(java.lang.String annualIncome) {
		set("annualIncome", annualIncome);
	}

	public java.lang.String getAnnualIncome() {
		return get("annualIncome");
	}

	public void setReceivedEndowmentInsurance(java.lang.String receivedEndowmentInsurance) {
		set("receivedEndowmentInsurance", receivedEndowmentInsurance);
	}

	public java.lang.String getReceivedEndowmentInsurance() {
		return get("receivedEndowmentInsurance");
	}

	public void setAllSubsidization(java.lang.String allSubsidization) {
		set("allSubsidization", allSubsidization);
	}

	public java.lang.String getAllSubsidization() {
		return get("allSubsidization");
	}

	public void setClaimMedicalExpenses(java.lang.String claimMedicalExpenses) {
		set("claimMedicalExpenses", claimMedicalExpenses);
	}

	public java.lang.String getClaimMedicalExpenses() {
		return get("claimMedicalExpenses");
	}

	public void setWageIncome(java.lang.String wageIncome) {
		set("wageIncome", wageIncome);
	}

	public java.lang.String getWageIncome() {
		return get("wageIncome");
	}

	public void setProductiveOutlays(java.lang.String productiveOutlays) {
		set("productiveOutlays", productiveOutlays);
	}

	public java.lang.String getProductiveOutlays() {
		return get("productiveOutlays");
	}

	public void setMedicalAid(java.lang.String medicalAid) {
		set("medicalAid", medicalAid);
	}

	public java.lang.String getMedicalAid() {
		return get("medicalAid");
	}

	public void setPropertyIncome(java.lang.String propertyIncome) {
		set("propertyIncome", propertyIncome);
	}

	public java.lang.String getPropertyIncome() {
		return get("propertyIncome");
	}

	public void setReceivedFamilyPlanningMoney(java.lang.String receivedFamilyPlanningMoney) {
		set("receivedFamilyPlanningMoney", receivedFamilyPlanningMoney);
	}

	public java.lang.String getReceivedFamilyPlanningMoney() {
		return get("receivedFamilyPlanningMoney");
	}

	public void setEcologicalCompensation(java.lang.String ecologicalCompensation) {
		set("ecologicalCompensation", ecologicalCompensation);
	}

	public java.lang.String getEcologicalCompensation() {
		return get("ecologicalCompensation");
	}

	public void setTrainingSubsidy(java.lang.Double trainingSubsidy) {
		set("trainingSubsidy", trainingSubsidy);
	}

	public java.lang.Double getTrainingSubsidy() {
		return get("trainingSubsidy");
	}

	public void setTrainingExpenditure(java.lang.Double trainingExpenditure) {
		set("trainingExpenditure", trainingExpenditure);
	}

	public java.lang.Double getTrainingExpenditure() {
		return get("trainingExpenditure");
	}

	public void setCashPolicySubsidies(java.lang.Double cashPolicySubsidies) {
		set("cashPolicySubsidies", cashPolicySubsidies);
	}

	public java.lang.Double getCashPolicySubsidies() {
		return get("cashPolicySubsidies");
	}

	public void setEducationalExpenditure(java.lang.Double educationalExpenditure) {
		set("educationalExpenditure", educationalExpenditure);
	}

	public java.lang.Double getEducationalExpenditure() {
		return get("educationalExpenditure");
	}

	public void setEducationalSubsidy(java.lang.Double educationalSubsidy) {
		set("educationalSubsidy", educationalSubsidy);
	}

	public java.lang.Double getEducationalSubsidy() {
		return get("educationalSubsidy");
	}

	public void setMedicalExpenditure(java.lang.Double medicalExpenditure) {
		set("medicalExpenditure", medicalExpenditure);
	}

	public java.lang.Double getMedicalExpenditure() {
		return get("medicalExpenditure");
	}

}
