package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTeamInfoDetail<M extends BaseTeamInfoDetail<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setCreateUserId(java.lang.String createUserId) {
		set("createUserId", createUserId);
	}

	public java.lang.String getCreateUserId() {
		return get("createUserId");
	}

	public void setInformationFillingTypeId(java.lang.String informationFillingTypeId) {
		set("informationFillingTypeId", informationFillingTypeId);
	}

	public java.lang.String getInformationFillingTypeId() {
		return get("informationFillingTypeId");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setAttachment(java.lang.String attachment) {
		set("attachment", attachment);
	}

	public java.lang.String getAttachment() {
		return get("attachment");
	}

}
