package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAccredited<M extends BaseAccredited<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setMemberId(java.lang.String memberId) {
		set("memberId", memberId);
	}

	public java.lang.String getMemberId() {
		return get("memberId");
	}

	public void setAccreditDepartmentId(java.lang.String accreditDepartmentId) {
		set("accreditDepartmentId", accreditDepartmentId);
	}

	public java.lang.String getAccreditDepartmentId() {
		return get("accreditDepartmentId");
	}

	public void setOrgPost(java.lang.String orgPost) {
		set("orgPost", orgPost);
	}

	public java.lang.String getOrgPost() {
		return get("orgPost");
	}

	public void setAccreditPlaceId(java.lang.String accreditPlaceId) {
		set("accreditPlaceId", accreditPlaceId);
	}

	public java.lang.String getAccreditPlaceId() {
		return get("accreditPlaceId");
	}

	public void setAccreditPostId(java.lang.String accreditPostId) {
		set("accreditPostId", accreditPostId);
	}

	public java.lang.String getAccreditPostId() {
		return get("accreditPostId");
	}

	public void setAccreditStart(java.util.Date accreditStart) {
		set("accreditStart", accreditStart);
	}

	public java.util.Date getAccreditStart() {
		return get("accreditStart");
	}

	public void setAccreditEnd(java.util.Date accreditEnd) {
		set("accreditEnd", accreditEnd);
	}

	public java.util.Date getAccreditEnd() {
		return get("accreditEnd");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("isValid");
	}

}
