package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHouse<M extends BaseHouse<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setFamilyId(java.lang.String familyId) {
		set("familyId", familyId);
	}

	public java.lang.String getFamilyId() {
		return get("familyId");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setArea(java.lang.Integer area) {
		set("area", area);
	}

	public java.lang.Integer getArea() {
		return get("area");
	}

	public void setHouseStructId(java.lang.String houseStructId) {
		set("houseStructId", houseStructId);
	}

	public java.lang.String getHouseStructId() {
		return get("houseStructId");
	}

	public void setFuelId(java.lang.String fuelId) {
		set("fuelId", fuelId);
	}

	public java.lang.String getFuelId() {
		return get("fuelId");
	}

	public void setProductArea(java.lang.Integer productArea) {
		set("productArea", productArea);
	}

	public java.lang.Integer getProductArea() {
		return get("productArea");
	}

	public void setLiveArea(java.lang.Integer liveArea) {
		set("liveArea", liveArea);
	}

	public java.lang.Integer getLiveArea() {
		return get("liveArea");
	}

	public void setLng(java.lang.Double lng) {
		set("lng", lng);
	}

	public java.lang.Double getLng() {
		return get("lng");
	}

	public void setLat(java.lang.Double lat) {
		set("lat", lat);
	}

	public java.lang.Double getLat() {
		return get("lat");
	}

	public void setHeight(java.lang.Double height) {
		set("height", height);
	}

	public java.lang.Double getHeight() {
		return get("height");
	}

}
