package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLeader<M extends BaseLeader<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}

	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setSexId(java.lang.String sexId) {
		set("sexId", sexId);
	}

	public java.lang.String getSexId() {
		return get("sexId");
	}

	public void setPoliticalStatusId(java.lang.String politicalStatusId) {
		set("politicalStatusId", politicalStatusId);
	}

	public java.lang.String getPoliticalStatusId() {
		return get("politicalStatusId");
	}

	public void setEducationalId(java.lang.String educationalId) {
		set("educationalId", educationalId);
	}

	public java.lang.String getEducationalId() {
		return get("educationalId");
	}

	public void setRaceId(java.lang.String raceId) {
		set("raceId", raceId);
	}

	public java.lang.String getRaceId() {
		return get("raceId");
	}

	public void setLevelId(java.lang.String levelId) {
		set("levelId", levelId);
	}

	public java.lang.String getLevelId() {
		return get("levelId");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setOrgId(java.lang.String orgId) {
		set("orgId", orgId);
	}

	public java.lang.String getOrgId() {
		return get("orgId");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setIDnumber(java.lang.String IDnumber) {
		set("IDnumber", IDnumber);
	}

	public java.lang.String getIDnumber() {
		return get("IDnumber");
	}

	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}

	public java.lang.String getWriter() {
		return get("writer");
	}

	public void setOperator(java.lang.String operator) {
		set("operator", operator);
	}

	public java.lang.String getOperator() {
		return get("operator");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("isValid");
	}

	public void setHelperTypeId(java.lang.String helperTypeId) {
		set("helperTypeId", helperTypeId);
	}

	public java.lang.String getHelperTypeId() {
		return get("helperTypeId");
	}

}
