package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFamilyEconomicSpecialSituationHappen<M extends BaseFamilyEconomicSpecialSituationHappen<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setFamilyEconomicId(java.lang.String familyEconomicId) {
		set("familyEconomicId", familyEconomicId);
	}

	public java.lang.String getFamilyEconomicId() {
		return get("familyEconomicId");
	}

	public void setFamilyId(java.lang.String familyId) {
		set("familyId", familyId);
	}

	public java.lang.String getFamilyId() {
		return get("familyId");
	}

	public void setParentTypeId(java.lang.String parentTypeId) {
		set("parentTypeId", parentTypeId);
	}

	public java.lang.String getParentTypeId() {
		return get("parentTypeId");
	}

	public void setTypeId(java.lang.String typeId) {
		set("typeId", typeId);
	}

	public java.lang.String getTypeId() {
		return get("typeId");
	}

	public void setIncreaseDecrease(java.lang.Integer increaseDecrease) {
		set("increaseDecrease", increaseDecrease);
	}

	public java.lang.Integer getIncreaseDecrease() {
		return get("increaseDecrease");
	}

	public void setAmount(java.lang.Integer amount) {
		set("amount", amount);
	}

	public java.lang.Integer getAmount() {
		return get("amount");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setCreatorId(java.lang.String creatorId) {
		set("creatorId", creatorId);
	}

	public java.lang.String getCreatorId() {
		return get("creatorId");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setOperatorId(java.lang.String operatorId) {
		set("operatorId", operatorId);
	}

	public java.lang.String getOperatorId() {
		return get("operatorId");
	}

	public void setOperatorTime(java.util.Date operatorTime) {
		set("operatorTime", operatorTime);
	}

	public java.util.Date getOperatorTime() {
		return get("operatorTime");
	}

}
