package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFamilyPovertyHappen<M extends BaseFamilyPovertyHappen<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setFamilyId(java.lang.String familyId) {
		set("familyId", familyId);
	}

	public java.lang.String getFamilyId() {
		return get("familyId");
	}

	public void setRalationTypeId(java.lang.String ralationTypeId) {
		set("ralationTypeId", ralationTypeId);
	}

	public java.lang.String getRalationTypeId() {
		return get("ralationTypeId");
	}

	public void setFamilyPropertyId(java.lang.String familyPropertyId) {
		set("familyPropertyId", familyPropertyId);
	}

	public java.lang.String getFamilyPropertyId() {
		return get("familyPropertyId");
	}

	public void setStatusTime(java.util.Date statusTime) {
		set("statusTime", statusTime);
	}

	public java.util.Date getStatusTime() {
		return get("statusTime");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setCreateUserId(java.lang.String createUserId) {
		set("createUserId", createUserId);
	}

	public java.lang.String getCreateUserId() {
		return get("createUserId");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("isValid");
	}

}
