package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProjectProgress<M extends BaseProjectProgress<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setProjectId(java.lang.String projectId) {
		set("projectId", projectId);
	}

	public java.lang.String getProjectId() {
		return get("projectId");
	}

	public void setProgress(java.lang.Float progress) {
		set("progress", progress);
	}

	public java.lang.Float getProgress() {
		return get("progress");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}

	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}

	public java.lang.String getWriter() {
		return get("writer");
	}

}
