package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductCondition<M extends BaseProductCondition<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setFamilyId(java.lang.String familyId) {
		set("familyId", familyId);
	}

	public java.lang.String getFamilyId() {
		return get("familyId");
	}

	public void setNoCredit(java.lang.Integer noCredit) {
		set("noCredit", noCredit);
	}

	public java.lang.Integer getNoCredit() {
		return get("noCredit");
	}

	public void setFamilyIncome(java.lang.Integer familyIncome) {
		set("familyIncome", familyIncome);
	}

	public java.lang.Integer getFamilyIncome() {
		return get("familyIncome");
	}

	public void setLivingMoney(java.lang.Integer livingMoney) {
		set("livingMoney", livingMoney);
	}

	public java.lang.Integer getLivingMoney() {
		return get("livingMoney");
	}

	public void setFamilyYearIncome(java.lang.Integer familyYearIncome) {
		set("familyYearIncome", familyYearIncome);
	}

	public java.lang.Integer getFamilyYearIncome() {
		return get("familyYearIncome");
	}

	public void setPersonYearIncome(java.lang.Integer personYearIncome) {
		set("personYearIncome", personYearIncome);
	}

	public java.lang.Integer getPersonYearIncome() {
		return get("personYearIncome");
	}

	public void setNursingMoney(java.lang.Integer nursingMoney) {
		set("nursingMoney", nursingMoney);
	}

	public java.lang.Integer getNursingMoney() {
		return get("nursingMoney");
	}

	public void setYearIncome(java.lang.Integer yearIncome) {
		set("yearIncome", yearIncome);
	}

	public java.lang.Integer getYearIncome() {
		return get("yearIncome");
	}

	public void setSubsidy(java.lang.Integer subsidy) {
		set("subsidy", subsidy);
	}

	public java.lang.Integer getSubsidy() {
		return get("subsidy");
	}

	public void setReimbursement(java.lang.Integer reimbursement) {
		set("reimbursement", reimbursement);
	}

	public java.lang.Integer getReimbursement() {
		return get("reimbursement");
	}

	public void setSalaryIncome(java.lang.Integer salaryIncome) {
		set("salaryIncome", salaryIncome);
	}

	public java.lang.Integer getSalaryIncome() {
		return get("salaryIncome");
	}

	public void setProductPay(java.lang.Integer productPay) {
		set("productPay", productPay);
	}

	public java.lang.Integer getProductPay() {
		return get("productPay");
	}

	public void setAimMoney(java.lang.Integer aimMoney) {
		set("aimMoney", aimMoney);
	}

	public java.lang.Integer getAimMoney() {
		return get("aimMoney");
	}

	public void setPropertyIncome(java.lang.Integer propertyIncome) {
		set("propertyIncome", propertyIncome);
	}

	public java.lang.Integer getPropertyIncome() {
		return get("propertyIncome");
	}

	public void setFamilyPlanningMoney(java.lang.Integer familyPlanningMoney) {
		set("familyPlanningMoney", familyPlanningMoney);
	}

	public java.lang.Integer getFamilyPlanningMoney() {
		return get("familyPlanningMoney");
	}

	public void setEcologyMoney(java.lang.Integer ecologyMoney) {
		set("ecologyMoney", ecologyMoney);
	}

	public java.lang.Integer getEcologyMoney() {
		return get("ecologyMoney");
	}

	public void setAverageIncome(java.lang.Double averageIncome) {
		set("averageIncome", averageIncome);
	}

	public java.lang.Double getAverageIncome() {
		return get("averageIncome");
	}

}
