package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRegionInfo<M extends BaseRegionInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setRegionId(java.lang.String regionId) {
		set("regionId", regionId);
	}

	public java.lang.String getRegionId() {
		return get("regionId");
	}

	public void setPopulation(java.lang.Integer population) {
		set("population", population);
	}

	public java.lang.Integer getPopulation() {
		return get("population");
	}

	public void setCount(java.lang.Integer count) {
		set("count", count);
	}

	public java.lang.Integer getCount() {
		return get("count");
	}

	public void setGroupCount(java.lang.Integer groupCount) {
		set("groupCount", groupCount);
	}

	public java.lang.Integer getGroupCount() {
		return get("groupCount");
	}

	public void setPercent(java.lang.Integer percent) {
		set("percent", percent);
	}

	public java.lang.Integer getPercent() {
		return get("percent");
	}

	public void setPartyMemberCount(java.lang.Integer partyMemberCount) {
		set("partyMemberCount", partyMemberCount);
	}

	public java.lang.Integer getPartyMemberCount() {
		return get("partyMemberCount");
	}

	public void setPoulationCount(java.lang.Integer poulationCount) {
		set("poulationCount", poulationCount);
	}

	public java.lang.Integer getPoulationCount() {
		return get("poulationCount");
	}

	public void setLowIncomeCount(java.lang.Integer lowIncomeCount) {
		set("lowIncomeCount", lowIncomeCount);
	}

	public java.lang.Integer getLowIncomeCount() {
		return get("lowIncomeCount");
	}

	public void setAverageArea(java.lang.String averageArea) {
		set("averageArea", averageArea);
	}

	public java.lang.String getAverageArea() {
		return get("averageArea");
	}

	public void setAverageForestryArea(java.lang.String averageForestryArea) {
		set("averageForestryArea", averageForestryArea);
	}

	public java.lang.String getAverageForestryArea() {
		return get("averageForestryArea");
	}

	public void setIsPoint(java.lang.Integer isPoint) {
		set("isPoint", isPoint);
	}

	public java.lang.Integer getIsPoint() {
		return get("isPoint");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}

	public java.lang.String getUserId() {
		return get("userId");
	}

	public void setCultivatedArea(java.lang.String cultivatedArea) {
		set("cultivatedArea", cultivatedArea);
	}

	public java.lang.String getCultivatedArea() {
		return get("cultivatedArea");
	}

	public void setIrrigatedArea(java.lang.String irrigatedArea) {
		set("irrigatedArea", irrigatedArea);
	}

	public java.lang.String getIrrigatedArea() {
		return get("irrigatedArea");
	}

	public void setFieldArea(java.lang.String fieldArea) {
		set("fieldArea", fieldArea);
	}

	public java.lang.String getFieldArea() {
		return get("fieldArea");
	}

	public void setLandArea(java.lang.String landArea) {
		set("landArea", landArea);
	}

	public java.lang.String getLandArea() {
		return get("landArea");
	}

	public void setForestryArea(java.lang.String forestryArea) {
		set("forestryArea", forestryArea);
	}

	public java.lang.String getForestryArea() {
		return get("forestryArea");
	}

	public void setBackForestryArea(java.lang.String backForestryArea) {
		set("backForestryArea", backForestryArea);
	}

	public java.lang.String getBackForestryArea() {
		return get("backForestryArea");
	}

	public void setFruitTreeArea(java.lang.String fruitTreeArea) {
		set("fruitTreeArea", fruitTreeArea);
	}

	public java.lang.String getFruitTreeArea() {
		return get("fruitTreeArea");
	}

	public void setGrassArea(java.lang.String grassArea) {
		set("grassArea", grassArea);
	}

	public java.lang.String getGrassArea() {
		return get("grassArea");
	}

	public void setWaterArea(java.lang.String waterArea) {
		set("waterArea", waterArea);
	}

	public java.lang.String getWaterArea() {
		return get("waterArea");
	}

	public void setEconomicArea(java.lang.String economicArea) {
		set("economicArea", economicArea);
	}

	public java.lang.String getEconomicArea() {
		return get("economicArea");
	}

	public void setGrossIncome(java.lang.String grossIncome) {
		set("grossIncome", grossIncome);
	}

	public java.lang.String getGrossIncome() {
		return get("grossIncome");
	}

	public void setHouseholdIncome(java.lang.String householdIncome) {
		set("householdIncome", householdIncome);
	}

	public java.lang.String getHouseholdIncome() {
		return get("householdIncome");
	}

	public void setPropertyIncome(java.lang.String propertyIncome) {
		set("propertyIncome", propertyIncome);
	}

	public java.lang.String getPropertyIncome() {
		return get("propertyIncome");
	}

	public void setTransferIncome(java.lang.String transferIncome) {
		set("transferIncome", transferIncome);
	}

	public java.lang.String getTransferIncome() {
		return get("transferIncome");
	}

	public void setTotalNetIncome(java.lang.String totalNetIncome) {
		set("totalNetIncome", totalNetIncome);
	}

	public java.lang.String getTotalNetIncome() {
		return get("totalNetIncome");
	}

	public void setTotalPerNetIncome(java.lang.String totalPerNetIncome) {
		set("totalPerNetIncome", totalPerNetIncome);
	}

	public java.lang.String getTotalPerNetIncome() {
		return get("totalPerNetIncome");
	}

	public void setTotalProductionExpenses(java.lang.String totalProductionExpenses) {
		set("totalProductionExpenses", totalProductionExpenses);
	}

	public java.lang.String getTotalProductionExpenses() {
		return get("totalProductionExpenses");
	}

	public void setTotalOtherExpenses(java.lang.String totalOtherExpenses) {
		set("totalOtherExpenses", totalOtherExpenses);
	}

	public java.lang.String getTotalOtherExpenses() {
		return get("totalOtherExpenses");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setShortDescription(java.lang.String shortDescription) {
		set("shortDescription", shortDescription);
	}

	public java.lang.String getShortDescription() {
		return get("shortDescription");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("isValid");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setOperator(java.lang.String operator) {
		set("operator", operator);
	}

	public java.lang.String getOperator() {
		return get("operator");
	}

	public void setPovertyTypeId(java.lang.String povertyTypeId) {
		set("povertyTypeId", povertyTypeId);
	}

	public java.lang.String getPovertyTypeId() {
		return get("povertyTypeId");
	}

	public void setAssignDate(java.util.Date assignDate) {
		set("assignDate", assignDate);
	}

	public java.util.Date getAssignDate() {
		return get("assignDate");
	}

	public void setAssignEndDate(java.util.Date assignEndDate) {
		set("assignEndDate", assignEndDate);
	}

	public java.util.Date getAssignEndDate() {
		return get("assignEndDate");
	}

	public void setHeadOfVillageCommitteeId(java.lang.String headOfVillageCommitteeId) {
		set("headOfVillageCommitteeId", headOfVillageCommitteeId);
	}

	public java.lang.String getHeadOfVillageCommitteeId() {
		return get("headOfVillageCommitteeId");
	}

	public void setHeadOfVillageCommitteeName(java.lang.String headOfVillageCommitteeName) {
		set("headOfVillageCommitteeName", headOfVillageCommitteeName);
	}

	public java.lang.String getHeadOfVillageCommitteeName() {
		return get("headOfVillageCommitteeName");
	}

	public void setVillageBranchSecretaryId(java.lang.String villageBranchSecretaryId) {
		set("villageBranchSecretaryId", villageBranchSecretaryId);
	}

	public java.lang.String getVillageBranchSecretaryId() {
		return get("villageBranchSecretaryId");
	}

	public void setVillageBranchSecretaryName(java.lang.String villageBranchSecretaryName) {
		set("villageBranchSecretaryName", villageBranchSecretaryName);
	}

	public java.lang.String getVillageBranchSecretaryName() {
		return get("villageBranchSecretaryName");
	}

	public void setPoorFamilyLeaderId(java.lang.String poorFamilyLeaderId) {
		set("poorFamilyLeaderId", poorFamilyLeaderId);
	}

	public java.lang.String getPoorFamilyLeaderId() {
		return get("poorFamilyLeaderId");
	}

	public void setPoorFamilyLeaderName(java.lang.String poorFamilyLeaderName) {
		set("poorFamilyLeaderName", poorFamilyLeaderName);
	}

	public java.lang.String getPoorFamilyLeaderName() {
		return get("poorFamilyLeaderName");
	}

}
