package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePublicService<M extends BasePublicService<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setYEAR(java.lang.Integer YEAR) {
		set("YEAR", YEAR);
	}

	public java.lang.Integer getYEAR() {
		return get("YEAR");
	}

	public void setWRITER(java.lang.String WRITER) {
		set("WRITER", WRITER);
	}

	public java.lang.String getWRITER() {
		return get("WRITER");
	}

	public void setCREATETIME(java.util.Date CREATETIME) {
		set("CREATETIME", CREATETIME);
	}

	public java.util.Date getCREATETIME() {
		return get("CREATETIME");
	}

	public void setNOWWRITER(java.lang.String NOWWRITER) {
		set("NOWWRITER", NOWWRITER);
	}

	public java.lang.String getNOWWRITER() {
		return get("NOWWRITER");
	}

	public void setNOWCREATETIME(java.util.Date NOWCREATETIME) {
		set("NOWCREATETIME", NOWCREATETIME);
	}

	public java.util.Date getNOWCREATETIME() {
		return get("NOWCREATETIME");
	}

	public void setCOTENTANDAREA(java.lang.String COTENTANDAREA) {
		set("COTENTANDAREA", COTENTANDAREA);
	}

	public java.lang.String getCOTENTANDAREA() {
		return get("COTENTANDAREA");
	}

	public void setCOMPLETEMONEY(java.lang.Integer COMPLETEMONEY) {
		set("COMPLETEMONEY", COMPLETEMONEY);
	}

	public java.lang.Integer getCOMPLETEMONEY() {
		return get("COMPLETEMONEY");
	}

	public void setFUNDATION(java.lang.Integer FUNDATION) {
		set("FUNDATION", FUNDATION);
	}

	public java.lang.Integer getFUNDATION() {
		return get("FUNDATION");
	}

	public void setDEPARTMENTMONEY(java.lang.Integer DEPARTMENTMONEY) {
		set("DEPARTMENTMONEY", DEPARTMENTMONEY);
	}

	public java.lang.Integer getDEPARTMENTMONEY() {
		return get("DEPARTMENTMONEY");
	}

	public void setSELFMONEY(java.lang.Integer SELFMONEY) {
		set("SELFMONEY", SELFMONEY);
	}

	public java.lang.Integer getSELFMONEY() {
		return get("SELFMONEY");
	}

}
