package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEducation<M extends BaseEducation<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setTypeId(java.lang.String typeId) {
		set("typeId", typeId);
	}

	public java.lang.String getTypeId() {
		return get("typeId");
	}

	public void setOrgId(java.lang.String orgId) {
		set("orgId", orgId);
	}

	public java.lang.String getOrgId() {
		return get("orgId");
	}

	public void setNumber(java.lang.Integer number) {
		set("number", number);
	}

	public java.lang.Integer getNumber() {
		return get("number");
	}

	public void setStartTime(java.util.Date startTime) {
		set("startTime", startTime);
	}

	public java.util.Date getStartTime() {
		return get("startTime");
	}

	public void setEndTime(java.util.Date endTime) {
		set("endTime", endTime);
	}

	public java.util.Date getEndTime() {
		return get("endTime");
	}

	public void setPersonCount(java.lang.Integer personCount) {
		set("personCount", personCount);
	}

	public java.lang.Integer getPersonCount() {
		return get("personCount");
	}

	public void setClassName(java.lang.String className) {
		set("className", className);
	}

	public java.lang.String getClassName() {
		return get("className");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setMajor(java.lang.String major) {
		set("major", major);
	}

	public java.lang.String getMajor() {
		return get("major");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}

	public java.lang.String getWriter() {
		return get("writer");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setNowWriter(java.lang.String nowWriter) {
		set("nowWriter", nowWriter);
	}

	public java.lang.String getNowWriter() {
		return get("nowWriter");
	}

	public void setNowCreateTime(java.util.Date nowCreateTime) {
		set("nowCreateTime", nowCreateTime);
	}

	public java.util.Date getNowCreateTime() {
		return get("nowCreateTime");
	}

}
