package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUnderwriter<M extends BaseUnderwriter<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setAdministrativeRegionId(java.lang.String administrativeRegionId) {
		set("administrativeRegionId", administrativeRegionId);
	}

	public java.lang.String getAdministrativeRegionId() {
		return get("administrativeRegionId");
	}

	public void setOrgId(java.lang.String orgId) {
		set("orgId", orgId);
	}

	public java.lang.String getOrgId() {
		return get("orgId");
	}

	public void setFamilyId(java.lang.String familyId) {
		set("familyId", familyId);
	}

	public java.lang.String getFamilyId() {
		return get("familyId");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}

	public java.lang.String getUserId() {
		return get("userId");
	}

	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}

	public java.lang.String getWriter() {
		return get("writer");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setOperator(java.lang.String operator) {
		set("operator", operator);
	}

	public java.lang.String getOperator() {
		return get("operator");
	}

	public void setOperatorTime(java.util.Date operatorTime) {
		set("operatorTime", operatorTime);
	}

	public java.util.Date getOperatorTime() {
		return get("operatorTime");
	}

	public void setTypeId(java.lang.String typeId) {
		set("typeId", typeId);
	}

	public java.lang.String getTypeId() {
		return get("typeId");
	}

	public void setContactPerson(java.lang.String contactPerson) {
		set("contactPerson", contactPerson);
	}

	public java.lang.String getContactPerson() {
		return get("contactPerson");
	}

	public void setRemain(java.lang.Integer remain) {
		set("remain", remain);
	}

	public java.lang.Integer getRemain() {
		return get("remain");
	}

}
