package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStatisticsPovertyReason<M extends BaseStatisticsPovertyReason<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setYear(java.lang.Integer year) {
		set("year", year);
	}

	public java.lang.Integer getYear() {
		return get("year");
	}

	public void setTotalCount(java.lang.Integer totalCount) {
		set("totalCount", totalCount);
	}

	public java.lang.Integer getTotalCount() {
		return get("totalCount");
	}

	public void setLackTechnologyCount(java.lang.Integer lackTechnologyCount) {
		set("lackTechnologyCount", lackTechnologyCount);
	}

	public java.lang.Integer getLackTechnologyCount() {
		return get("lackTechnologyCount");
	}

	public void setLackLaborCount(java.lang.Integer lackLaborCount) {
		set("lackLaborCount", lackLaborCount);
	}

	public java.lang.Integer getLackLaborCount() {
		return get("lackLaborCount");
	}

	public void setLackMoneyCount(java.lang.Integer lackMoneyCount) {
		set("lackMoneyCount", lackMoneyCount);
	}

	public java.lang.Integer getLackMoneyCount() {
		return get("lackMoneyCount");
	}

	public void setStudayCount(java.lang.Integer studayCount) {
		set("studayCount", studayCount);
	}

	public java.lang.Integer getStudayCount() {
		return get("studayCount");
	}

	public void setDisasterCount(java.lang.Integer disasterCount) {
		set("disasterCount", disasterCount);
	}

	public java.lang.Integer getDisasterCount() {
		return get("disasterCount");
	}

	public void setLackWaterCount(java.lang.Integer lackWaterCount) {
		set("lackWaterCount", lackWaterCount);
	}

	public java.lang.Integer getLackWaterCount() {
		return get("lackWaterCount");
	}

	public void setSelfCount(java.lang.Integer selfCount) {
		set("selfCount", selfCount);
	}

	public java.lang.Integer getSelfCount() {
		return get("selfCount");
	}

	public void setDeformityCount(java.lang.Integer deformityCount) {
		set("deformityCount", deformityCount);
	}

	public java.lang.Integer getDeformityCount() {
		return get("deformityCount");
	}

	public void setTrafficCount(java.lang.Integer trafficCount) {
		set("trafficCount", trafficCount);
	}

	public java.lang.Integer getTrafficCount() {
		return get("trafficCount");
	}

	public void setOtherCount(java.lang.Integer otherCount) {
		set("otherCount", otherCount);
	}

	public java.lang.Integer getOtherCount() {
		return get("otherCount");
	}

}
