package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMember<M extends BaseMember<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setSexId(java.lang.String sexId) {
		set("sexId", sexId);
	}

	public java.lang.String getSexId() {
		return get("sexId");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}

	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setIDnumber(java.lang.String IDnumber) {
		set("IDnumber", IDnumber);
	}

	public java.lang.String getIDnumber() {
		return get("IDnumber");
	}

	public void setPoliticalStatusId(java.lang.String politicalStatusId) {
		set("politicalStatusId", politicalStatusId);
	}

	public java.lang.String getPoliticalStatusId() {
		return get("politicalStatusId");
	}

	public void setEducationalId(java.lang.String educationalId) {
		set("educationalId", educationalId);
	}

	public java.lang.String getEducationalId() {
		return get("educationalId");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("isValid");
	}

	public void setRaceId(java.lang.String raceId) {
		set("raceId", raceId);
	}

	public java.lang.String getRaceId() {
		return get("raceId");
	}

	public void setOrgId(java.lang.String orgId) {
		set("orgId", orgId);
	}

	public java.lang.String getOrgId() {
		return get("orgId");
	}

	public void setPost(java.lang.String post) {
		set("post", post);
	}

	public java.lang.String getPost() {
		return get("post");
	}

	public void setGroupId(java.lang.String groupId) {
		set("groupId", groupId);
	}

	public java.lang.String getGroupId() {
		return get("groupId");
	}

	public void setRoleOfGroupId(java.lang.String roleOfGroupId) {
		set("roleOfGroupId", roleOfGroupId);
	}

	public java.lang.String getRoleOfGroupId() {
		return get("roleOfGroupId");
	}

	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}

	public java.lang.String getWriter() {
		return get("writer");
	}

	public void setOperator(java.lang.String operator) {
		set("operator", operator);
	}

	public java.lang.String getOperator() {
		return get("operator");
	}

	public void setStringBirthday(java.lang.String stringBirthday) {
		set("stringBirthday", stringBirthday);
	}

	public java.lang.String getStringBirthday() {
		return get("stringBirthday");
	}

	public void setUseId(java.lang.String useId) {
		set("useId", useId);
	}

	public java.lang.String getUseId() {
		return get("useId");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setAccreditDepartmentName(java.lang.String accreditDepartmentName) {
		set("accreditDepartmentName", accreditDepartmentName);
	}

	public java.lang.String getAccreditDepartmentName() {
		return get("accreditDepartmentName");
	}

	public void setAccreditDepartmentId(java.lang.String accreditDepartmentId) {
		set("accreditDepartmentId", accreditDepartmentId);
	}

	public java.lang.String getAccreditDepartmentId() {
		return get("accreditDepartmentId");
	}

	public void setOrgPost(java.lang.String orgPost) {
		set("orgPost", orgPost);
	}

	public java.lang.String getOrgPost() {
		return get("orgPost");
	}

	public void setAccreditPlaceId(java.lang.String accreditPlaceId) {
		set("accreditPlaceId", accreditPlaceId);
	}

	public java.lang.String getAccreditPlaceId() {
		return get("accreditPlaceId");
	}

	public void setAccreditStart(java.util.Date accreditStart) {
		set("accreditStart", accreditStart);
	}

	public java.util.Date getAccreditStart() {
		return get("accreditStart");
	}

	public void setAccreditEnd(java.util.Date accreditEnd) {
		set("accreditEnd", accreditEnd);
	}

	public java.util.Date getAccreditEnd() {
		return get("accreditEnd");
	}

	public void setAccreditPostId(java.lang.String accreditPostId) {
		set("accreditPostId", accreditPostId);
	}

	public java.lang.String getAccreditPostId() {
		return get("accreditPostId");
	}

}
