package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCollectiveEconomy<M extends BaseCollectiveEconomy<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setRegionId(java.lang.String regionId) {
		set("regionId", regionId);
	}

	public java.lang.String getRegionId() {
		return get("regionId");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setValligerId(java.lang.String valligerId) {
		set("valligerId", valligerId);
	}

	public java.lang.String getValligerId() {
		return get("valligerId");
	}

	public void setValligerName(java.lang.String valligerName) {
		set("valligerName", valligerName);
	}

	public java.lang.String getValligerName() {
		return get("valligerName");
	}

	public void setTotalPrice(java.lang.Double totalPrice) {
		set("totalPrice", totalPrice);
	}

	public java.lang.Double getTotalPrice() {
		return get("totalPrice");
	}

	public void setCreatorId(java.lang.String creatorId) {
		set("creatorId", creatorId);
	}

	public java.lang.String getCreatorId() {
		return get("creatorId");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
