package com.arnold.server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTeamInfo<M extends BaseTeamInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setCreateUserId(java.lang.String createUserId) {
		set("createUserId", createUserId);
	}

	public java.lang.String getCreateUserId() {
		return get("createUserId");
	}

	public void setInformationFillingTypeId(java.lang.String informationFillingTypeId) {
		set("informationFillingTypeId", informationFillingTypeId);
	}

	public java.lang.String getInformationFillingTypeId() {
		return get("informationFillingTypeId");
	}

	public void setUploadNum(java.lang.Integer uploadNum) {
		set("uploadNum", uploadNum);
	}

	public java.lang.Integer getUploadNum() {
		return get("uploadNum");
	}

	public void setUploadTime(java.util.Date uploadTime) {
		set("uploadTime", uploadTime);
	}

	public java.util.Date getUploadTime() {
		return get("uploadTime");
	}

}
